#!/usr/bin/env python3
"""Generate Bluefin custom image config from CachyOS package manifest.

Reads states/data/packages.yaml, maps Arch packages to Fedora equivalents,
and produces:
  - Containerfile        (rpm-ostree layers)
  - flatpak.list         (desktop apps)
  - brew.Brewfile        (dev/CLI tools via Homebrew)
  - mapping.yaml         (full Arch→Fedora mapping)
  - missing.txt          (no Fedora equivalent — needs COPR/build)
  - services.list        (systemd services to migrate)
"""

import yaml
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# ── Package naming differences Arch → Fedora ──────────────────────────
# Key: Arch package name, Value: Fedora package name (None = not available)
FEDORA_RENAME = {
    "base": "filesystem",
    "base-devel": None,  # meta package, individual tools exist
    "linux": None,  # kernel, handled by Bluefin base
    "linux-headers": None,
    "linux-cachyos-headers": None,
    "linux-firmware": "linux-firmware",
    "amd-ucode": "amd-ucode-firmware",
    "broot": "broot",
    "firefox": "firefox",  # but use flatpak
    "chromium": None,  # chromium-freeworld in RPMFusion
    "gimp": "gimp",  # or flatpak
    "eza": "eza",
    "dunst": "dunst",
    "hyprland": "hyprland",
    "hypridle": "hypridle",
    "hyprlock": "hyprlock",
    "hyprpicker": "hyprpicker",
    "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
    "wl-clipboard": "wl-clipboard",
    "wlr-randr": "wlr-randr",
    "rofi": "rofi",
    "wofi": "wofi",
    "waybar": "waybar",
    "swayimg": "swayimg",
    "swayosd": None,
    "slurp": "slurp",
    "grim": "grim",
    "satty": None,
    "swappy": None,
    "gimp": "gimp",
    "fd": "fd-find",
    "bat": "bat",
    "ripgrep": "ripgrep",
    "fzf": "fzf",
    "zoxide": "zoxide",
    "dust": "dust",
    "bottom": "bottom",
    "btop": "btop",
    "neovim": "neovim",
    "helix": "helix",
    "git": "git",
    "curl": "curl",
    "wget": "wget",
    "wget2": "wget2",
    "jq": "jq",
    "yq": None,  # yq in Fedora is python wrapper, use go-yq or mikefarah/yq
    "go-yq": None,  # mikefarah/yq not in fedora, brew
    "httpie": "httpie",
    "xh": "xh",
    "curlie": None,  # not in fedora
    "tealdeer": "tealdeer",
    "shellcheck": "ShellCheck",
    "yamllint": "yamllint",
    "ruff": "ruff",
    "taplo-cli": None,  # brew
    "pre-commit": "pre-commit",
    "python-pipx": "pipx",
    "python-poetry": "poetry",
    "python-orjson": "python3-orjson",
    "python-numpy": "python3-numpy",
    "python-mutagen": "python3-mutagen",
    "python-faker": "python3-faker",
    "python-internetarchive": None,
    "python-ascii_magic": None,
    "python-rapidgzip": None,
    "pipx": "pipx",
    "uv": "uv",
    "nodejs": "nodejs",
    "npm": None,  # included in nodejs
    "ruby": "ruby",
    "gdb": "gdb",
    "clang": "clang",
    "lldb": "lldb",
    "cmake": "cmake",
    "meson": "meson",
    "ninja": "ninja-build",
    "openblas": "openblas",
    "fennel": None,  # not in fedora, but in luarocks
    "lua-language-server": "lua-language-server",
    "lua53": "lua",
    "patchelf": "patchelf",
    "subversion": "subversion",
    "docker": None,  # use podman
    "podman": "podman",
    "skopeo": "skopeo",
    "nerdctl": None,  # not in fedora
    "containerd": "containerd",
    "distrobox": "distrobox",
    "just": "just",
    "direnv": "direnv",
    "gh": "gh",  # github-cli
    "github-cli": "gh",
    "git-lfs": "git-lfs",
    "git-delta": "git-delta",
    "git-filter-repo": "git-filter-repo",
    "git-crypt": "git-crypt",
    "gitleaks": None,  # brew
    "gist": None,
    "jujutsu": "jj",
    "sad": "sad",
    "tig": "tig",
    "diff-so-fancy": "diff-so-fancy",
    "difftastic": "difftastic",
    "onefetch": "onefetch",
    "scc": None,  # brew
    "mpv": "mpv",
    "ffmpeg": "ffmpeg-free",  # or ffmpeg from rpmfusion
    "imagemagick": "ImageMagick",
    "yt-dlp": "yt-dlp",
    "mpd": "mpd",
    "mpc": "mpc",
    "rmpc": None,  # brew
    "zathura": "zathura",
    "zathura-pdf-poppler": "zathura-pdf-poppler",
    "pipewire": "pipewire",  # in Bluefin base
    "pavucontrol": "pavucontrol",
    "pwvucontrol": "pwvucontrol",
    "qpwgraph": "qpwgraph",
    "telegram-desktop": "telegram-desktop",  # or flatpak
    "ollama": "ollama",
    "discord": None,  # flatpak
    "signal-desktop": None,  # flatpak
    "vivaldi": None,  # not in fedora
    "librewolf": "librewolf",
    "zen-browser-bin": "zen-browser",  # may be flatpak only
    "floorp": None,  # flatpak
    "spotify": None,  # flatpak
    "figma-linux": None,  # flatpak (figma)
    "obs-studio": "obs-studio",
    "krita": "krita",
    "blender": "blender",
    "darktable": "darktable",
    "rawtherapee": "rawtherapee",
    "inkscape": "inkscape",
    "libreoffice": "libreoffice",
    "thunderbird": "thunderbird",
    "keepassxc": "keepassxc",
    "gnome-keyring": "gnome-keyring",
    "seahorse": "seahorse",
    "gnome-control-center": "gnome-control-center",
    "gnome-tweaks": "gnome-tweaks",
    "gnome-extensions": "gnome-extensions-app",
    "gnome-shell": "gnome-shell",
    "gnome-console": "gnome-console",
    "gnome-terminal": "gnome-terminal",
    "gnome-text-editor": "gnome-text-editor",
    "gnome-calculator": "gnome-calculator",
    "gnome-calendar": "gnome-calendar",
    "gnome-characters": "gnome-characters",
    "gnome-clocks": "gnome-clocks",
    "gnome-weather": "gnome-weather",
    "gnome-maps": "gnome-maps",
    "gnome-contacts": "gnome-contacts",
    "gnome-music": "gnome-music",
    "gnome-logs": "gnome-logs",
    "gnome-system-monitor": "gnome-system-monitor",
    "gnome-disk-utility": "gnome-disk-utility",
    "gnome-font-viewer": "gnome-font-viewer",
    "gnome-color-manager": "gnome-color-manager",
    "gnome-software": "gnome-software",
    "gnome-menus": "gnome-menus",
    "gnome-session": "gnome-session",
    "gnome-settings-daemon": "gnome-settings-daemon",
    "gnome-remote-desktop": "gnome-remote-desktop",
    "gnome-user-docs": "gnome-user-docs",
    "gnome-user-share": "gnome-user-share",
    "gnome-tour": "gnome-tour",
    "gnome-backgrounds": "gnome-backgrounds",
    "nautilus": "nautilus",
    "evince": "evince",
    "papers": "papers",
    "sushi": "sushi",
    "epiphany": "epiphany",
    "simple-scan": "simple-scan",
    "loupe": "loupe",
    "yed": None,  # not in fedora
    "yelp": "yelp",
    "localsearch": "tracker",  # not sure
    "tracker-miners": "tracker-miners",
    "xdg-desktop-portal": "xdg-desktop-portal",
    "xdg-desktop-portal-gnome": "xdg-desktop-portal-gnome",
    "xdg-desktop-portal-gtk": "xdg-desktop-portal-gtk",
    "xdg-user-dirs-gtk": "xdg-user-dirs-gtk",
    "xdg-utils": "xdg-utils",
    "flatpak": "flatpak",
    "wine": "wine",
    "gamemode": "gamemode",
    "gamescope": "gamescope",
    "mangohud": "mangohud",
    "lutris": "lutris",
    "steam": "steam",
    "proton-cachyos": None,  # Arch specific
    "proton-ge-custom-bin": None,  # AUR, use protonup-qt or manual
    "nethack": "nethack",
    "dosbox": "dosbox",
    "nvtop": "nvtop",
    "amdgpu_top": None,  # AUR
    "corectrl": "corectrl",
    "openrgb": "openrgb",
    "kitty": "kitty",
    "ghostty": "ghostty",
    "alacritty": "alacritty",
    "foot": "foot",
    "tmux": "tmux",
    "zellij": "zellij",
    "zsh": "zsh",
    "fish": "fish",
    "oh-my-posh": None,  # brew
    "starship": "starship",
    "chezmoi": "chezmoi",
    "yt-dlp": "yt-dlp",
    "gallery-dl": "gallery-dl",
    "rclone": "rclone",
    "borg": "borgbackup",
    "gopass": "gopass",
    "pass": "pass",
    "age": "age",
    "ssh-to-age": None,  # AUR
    "yubikey-manager": "yubikey-manager",
    "ccid": "pcsc-tools",
    "pcsc-tools": "pcsc-tools",
    "escrypt": None,  # not in fedora
    "sops": "sops",
    "git-crypt": "git-crypt",
    "lynis": "lynis",
    "rkhunter": None,
    "vim": "vim",
    "nano": "nano",
    "micro": "micro",
    "cmatrix": "cmatrix",
    "neofetch": "fastfetch",  # neofetch deprecated
    "fastfetch": "fastfetch",
    "cowsay": "cowsay",
    "fortune-mod": "fortune-mod",
    "figlet": "figlet",
    "toilet": "toilet",
    "lolcat": "lolcat",
    "cava": "cava",
    "qrencode": "qrencode",
    "chafa": "chafa",
    "viu": "viu",
    "asciinema": "asciinema",
    "parallel": "parallel",
    "moreutils": "moreutils",
    "pv": "pv",
    "progress": "progress",
    "dua-cli": "dua-cli",
    "choose": "choose",
    "ouch": "ouch",
    "hexyl": "hexyl",
    "bandwhich": "bandwhich",
    "procs": "procs",
    "erased": None,
    "doggo": "doggo",
    "grex": "grex",
    "htmlq": "htmlq",
    "miller": "miller",
    "xsv": "xsv",
    "csvkit": "csvkit",
    "jql": None,  # brew
    "jgrep": None,  # brew
    "fx": None,  # npm
    "dive": None,  # brew
    "ctop": "ctop",
    "lazydocker": None,  # brew
    "lazygit": "lazygit",
    "gitui": "gitui",
    "tokei": "tokei",
    "hyperfine": "hyperfine",
    "du-dust": "dust",
    "erdtree": "erdtree",
    "ncdu": "ncdu",
    "gdu": "gdu",
    "duf": "duf",
    "tree": "tree",
    "broot": "broot",
    "yazi": "yazi",
    "lf": "lf",
    "ranger": "ranger",
    "nnn": "nnn",
    "tmsu": None,  # not in fedora
    "recoll": "recoll",
    "fclones": "fclones",
    "rmlint": None,  # AUR
    "gdu": "gdu",
    "zip": "zip",
    "unzip": "unzip",
    "p7zip": "p7zip",
    "unar": "unar",
    "unarchiver": None,  # AUR
    "atool": None,
    "patool": None,  # AUR
    "pigz": "pigz",
    "pbzip2": "pbzip2",
    "lbzip2": "lbzip2",
    "zstd": "zstd",
    "xz": "xz",
    "tesseract": "tesseract",
    "tesseract-data-eng": "tesseract-langpack-eng",
    "tesseract-data-rus": "tesseract-langpack-rus",
    "optipng": "optipng",
    "jpegoptim": "jpegoptim",
    "pngquant": "pngquant",
    "scour": "scour",
    "gifski": "gifski",
    "ffmpegthumbnailer": "ffmpegthumbnailer",
    "mediainfo": "mediainfo",
    "perl-image-exiftool": "perl-Image-ExifTool",
    "id3v2": "id3v2",
    "picard": "picard",
    "beets": "beets",
    "chromaprint": "chromaprint",
    "cdparanoia": "cdparanoia",
    "sox": "sox",
    "flac": "flac",
    "opus-tools": "opus-tools",
    "wavpack": "wavpack",
    "shntool": "shntool",
    "cuetools": "cuetools",
    "mp3val": "mp3val",
    "sonic-visualiser": "sonic-visualiser",
    "carla": "carla",
    "lsp-plugins": "lsp-plugins",
    "easyeffects": "easyeffects",
    "ffado": "ffado",
    "ardour": "ardour6",
    "audacity": "audacity",
    "abduco": "abduco",
    "dvtm": "dvtm",
    "entr": "entr",
    "moreutils": "moreutils",
    "inotify-tools": "inotify-tools",
    "fswatch": None,  # brew
    "watchexec": "watchexec",
    "jaq": "jaq",  # standalone jq-like
    "mtr": "mtr",
    "nmap": "nmap",
    "tcpdump": "tcpdump",
    "wireshark-cli": "wireshark-cli",
    "nethogs": "nethogs",
    "iptraf-ng": "iptraf-ng",
    "bmon": "bmon",
    "vnstat": "vnstat",
    "speedtest-cli": "speedtest-cli",
    "cloudflare-speed-cli": None,  # not in fedora
    "iperf3": "iperf3",
    "fping": "fping",
    "whois": "whois",
    "geoip": "geoipupdate",
    "netcat": "nmap-ncat",
    "openbsd-netcat": "netcat",
    "socat": "socat",
    "freerdp": "freerdp",
    "remmina": "remmina",
    "virt-manager": "virt-manager",
    "virt-viewer": "virt-viewer",
    "qemu-desktop": "qemu",
    "edk2-ovmf": "edk2-ovmf",
    "tailscale": "tailscale",
    "wireguard-tools": "wireguard-tools",
    "openvpn": "openvpn",
    "networkmanager": "NetworkManager",
    "network-manager-applet": "network-manager-applet",
    "nm-connection-editor": "nm-connection-editor",
    "bluez": "bluez",
    "bluez-utils": "bluez",
    "iwd": "iwd",
    "dnsmasq": "dnsmasq",
    "unbound": "unbound",
    "avahi": "avahi",
    "nss-mdns": "nss-mdns",
    "firewalld": "firewalld",
    "ufw": "ufw",
    "dhcpcd": None,  # dhcp-client instead
    "smartmontools": "smartmontools",
    "lm_sensors": "lm_sensors",
    "hwinfo": "hwinfo",
    "lshw": "lshw",
    "inxi": "inxi",
    "neofetch": "fastfetch",
    "pciutils": "pciutils",
    "usbutils": "usbutils",
    "sysstat": "sysstat",
    "strace": "strace",
    "ltrace": "ltrace",
    "valgrind": "valgrind",
    "strace": "strace",
    "bpftrace": "bpftrace",
    "perf": "perf",
    "iotop-c": "iotop-c",
    "ioping": "ioping",
    "fio": "fio",
    "stress-ng": "stress-ng",
    "s-tui": None,  # can pip install
    "powertop": "powertop",
    "turbostat": "kernel-tools",
    "cpupower": "kernel-tools",
    "cpufetch": None,  # AUR
    "memtester": "memtester",
    "ddrescue": "ddrescue",
    "testdisk": "testdisk",
    "parted": "parted",
    "gptfdisk": "gptfdisk",
    "efibootmgr": "efibootmgr",
    "sbctl": "sbctl",
    "systemd-resolvconf": None,  # systemd-resolved is built-in
    "zram-generator": "zram-generator",
    "etckeeper": "etckeeper",
    "dconf-editor": "dconf-editor",
    "dconf": "dconf",
    "fwupd": "fwupd",
    "snapper": "snapper",
    "timeshift": "timeshift",
    "htop": "htop",
    "glances": "glances",
    "gotop": None,  # brew
    "bpytop": "bpytop",
    "bashtop": "bashtop",
    "nvtop": "nvtop",
    "iftop": "iftop",
    "atop": "atop",
    "acpi": "acpi",
    "acpid": "acpid",
    "upower": "upower",
    "tlp": "tlp",
    "powertop": "powertop",
    "dkms": "akmods",
    "kmod": "kmod",
    "kexec-tools": "kexec-tools",
    "mc": "mc",
    "ranger": "ranger",
    "nnn": "nnn",
    "pcmanfm": "pcmanfm",
    "udiskie": "udiskie",
    "udisks2": "udisks2",
    "gvfs": "gvfs",
    "gvfs-mtp": "gvfs-mtp",
    "gvfs-smb": "gvfs-smb",
    "gvfs-afc": "gvfs-afc",
    "gvfs-dnssd": "gvfs-dnssd",
    "gvfs-goa": "gvfs-goa",
    "gvfs-gphoto2": "gvfs-gphoto2",
    "gvfs-nfs": "gvfs-nfs",
    "gvfs-onedrive": None,  # not in fedora
    "gvfs-wsdd": None,  # not in fedora
    "arch-install-scripts": None,
    "pacman-contrib": None,
    "rebuild-detector": None,  # Arch-specific
    "cups": "cups",
    "cups-pk-helper": "cups-pk-helper",
    "system-config-printer": "system-config-printer",
    "sane-backends": "sane-backends",
    "sane-frontends": "sane-frontends",
    "xsane": "xsane",
    "hplip": "hplip",
    "liquidctl": "liquidctl",
    "OpenCL": "clinfo",
    "clinfo": "clinfo",
    "ocl-icd": "ocl-icd",
    "glew": "glew",
    "glfw": "glfw",
    "freeglut": "freeglut",
    "vulkan-tools": "vulkan-tools",
    "vulkan-headers": "vulkan-headers",
    "lib32-vulkan-radeon": None,  # 32-bit not in fedora
    "doxygen": "doxygen",
    "graphviz": "graphviz",
    "plantuml": "plantuml",
    "cargo": "cargo",
    "rustup": "rustup",
    "rust-analyzer": "rust-analyzer",
    "golang": "golang",
    "buck2": None,  # not in fedora
    "luarocks": "luarocks",
    "lua": "lua",
    "julia": "julia",
    "r": "R",
    "racket": "racket",
    "guile": "guile",
    "sbcl": "sbcl",
    "coq": "coq",
    "idris": "idris",
    "agda": "Agda",
    "texlive-basic": "texlive-base",
    "texlive-latex": "texlive-latex",
    "pandoc-cli": "pandoc",
    "ghostscript": "ghostscript",
    "hunspell-ru": "hunspell-ru",
    "aspell": "aspell",
    "aspell-en": "aspell-en",
    "ispell": "aspell",
    "nuspell": "nuspell",
    "fonts-noto": "google-noto-sans-fonts",
    "noto-fonts-cjk": "google-noto-cjk-fonts",
    "noto-fonts-emoji": "google-noto-emoji-fonts",
    "ttf-jetbrains-mono-nerd": "jetbrains-mono-fonts",
    "ttf-nerd-fonts-symbols": None,
    "iosevka-neg-fonts": None,  # custom font
    "ttf-dejavu": "dejavu-sans-fonts",
    "ttf-liberation": "liberation-fonts",
    "powerline-fonts": "powerline-fonts",
    "awesome-terminal-fonts": None,
    "freetype2": "freetype",
    "fontconfig": "fontconfig",
    "xorg-server": "xorg-x11-server-Xorg",
    "xorg-xinit": "xorg-x11-xinit",
    "xorg-xrandr": "xorg-x11-server-utils",
    "xorg-xdpyinfo": "xorg-x11-utils",
    "xf86-video-amdgpu": "xorg-x11-drv-amdgpu",
    "xf86-video-ati": "xorg-x11-drv-ati",
    "xclip": "xclip",
    "xsel": "xsel",
    "wlroots": "wlroots",
    "gtk3": "gtk3",
    "gtk4": "gtk4",
    "qt5ct": "qt5ct",
    "qt6ct": "qt6ct",
    "qt5-wayland": "qt5-qtwayland",
    "qt6-wayland": "qt6-qtwayland",
    "breeze": "breeze",
    "breeze-icons": "breeze-icon-theme",
    "plasma-desktop": "plasma-desktop",
    "plasma-wayland-session": "plasma-workspace-wayland",
    "plasma-workspace": "plasma-workspace",
    "polkit-kde-agent": "polkit-kde",
    "konsole": "konsole5",
    "kvantum": "kvantum",
    "kvantum-qt5": "kvantum",
    "kate": "kate",
    "ark": "ark",
    "dolphin": "dolphin",
    "gwenview": "gwenview",
    "okular": "okular",
    "spectacle": "spectacle",
    "filelight": "filelight",
    "gdm": "gdm",
    "sddm": "sddm",
    "lightdm": "lightdm",
    "greetd": "greetd",
    "uwsm": "uwsm",
    "cosmic-greeter": None,  # not in fedora
    "cosmic": None,  # COSMIC desktop
    "com.system76.CosmicGreeter": None,
    "niri": "niri",
    "quickshell": None,  # AUR
    "vicinae-bin": None,  # AUR
    "dmenu": "dmenu",
    "rofi-file-browser-extended": None,  # AUR
    "plocate": "plocate",
    "mlocate": "mlocate",
    "sudo": "sudo",
    "polkit": "polkit",
    "samba": "samba",
    "nfs-utils": "nfs-utils",
    "cifs-utils": "cifs-utils",
    "sshfs": "fuse-sshfs",
    "rsync": "rsync",
    "android-tools": "android-tools",
    "scrcpy": "scrcpy",
    "heif-gdk-pixbuf": None,
    "libheif": "libheif",
    "libraw": "LibRaw",
    "exfatprogs": "exfatprogs",
    "ntfs-3g": "ntfs-3g",
    "btrfs-progs": "btrfs-progs",
    "xfsprogs": "xfsprogs",
    "dosfstools": "dosfstools",
    "mtools": "mtools",
    "lvm2": "lvm2",
    "cryptsetup": "cryptsetup",
    "mdadm": "mdadm",
    "hdparm": "hdparm",
    "sdparm": "sdparm",
    "lsof": "lsof",
    "multipath-tools": "device-mapper-multipath",
    "sl": "sl",
    "units": "units",
    "rig": None,  # not in fedora
    "ponysay": None,  # not in fedora
    "cmatrix": "cmatrix",
    "asciiquarium": None,  # perl module
    "espeak": "espeak",
    "espeak-ng": "espeak-ng",
    "festival": "festival",
    "pico2wave": None,  # not in fedora
    "mbrola": None,  # not in fedora
    "orca": "orca",
    "speech-dispatcher": "speech-dispatcher",
    "malcontent": "malcontent",
    "malcontent-control": "malcontent-control",
    "gnome-shell-extension": None,  # part of gnome-shell
    "albert": None,  # not in fedora
    "ulauncher": None,  # not in fedora
    "synapse": "synapse",
    "kupfer": None,  # not in fedora
    "ulauncher": None,
    "anyrun": None,  # not in fedora
    "tofi": "tofi",
    "bemenu": "bemenu",
    "fuzzel": "fuzzel",
    "swaybg": "swaybg",
    "swayidle": "swayidle",
    "swaylock": "swaylock",
    "wlogout": None,  # AUR
    "wlr-which-key": None,  # AUR
    "wayvnc": "wayvnc",
    "waypipe": "waypipe",
    "wtype": "wtype",
    "ydotool": "ydotool",
    "wev": "wev",
    "wf-recorder": "wf-recorder",
    "wl-gammactl": "wl-gammactl",
    "wl-color-picker": None,
    "wl-mirror": "wl-mirror",
    "imv": "imv",
    "mpv-mpris": "mpv-mpris",
    "playerctl": "playerctl",
    "brightnessctl": "brightnessctl",
    "light": "light",
    "ddccontrol": "ddccontrol",
    "gddccontrol": "gddccontrol",
    "kanata": "kanata",
    "keyd": "keyd",
    "interception-tools": "interception-tools",
    "espanso": "espanso",
    "copyq": "copyq",
    "cliphist": "cliphist",
    "greenclip": None,  # not in fedora
    "xsel": "xsel",
    "xclip": "xclip",
    "wl-clipboard": "wl-clipboard",
    "wl-paste": "wl-clipboard",
    "resvg": "resvg",
    "inkscape": "inkscape",
    "dia": "dia",
    "gpick": "gpick",
    "gcolor3": "gcolor3",
    "swappy": None,  # AUR
    "satty": None,  # AUR
    "flameshot": "flameshot",
    "kooha": "kooha",
    "peek": "peek",
    "minder": None,  # not in fedora
    "xmind": None,  # not in fedora
    "drawio": None,  # flatpak
    "pinta": "pinta",
    "mypaint": "mypaint",
    "aseprite": None,  # not in fedora
    "grafana": "grafana",
    "prometheus": "prometheus",
    "loki": "loki",
    "promtail": None,  # part of loki or separate
    "alertmanager": None,  # not in fedora
    "node-exporter": "prometheus-node_exporter",
    "ntfy": "ntfy",
    "syncthing": "syncthing",
    "transmission-cli": "transmission",
    "transmission-daemon": "transmission-daemon",
    "qbittorrent": "qbittorrent",
    "qbittorrent-nox": None,
    "rustmission": None,  # AUR
    "jellyfin": "jellyfin",
    "jellyfin-server": "jellyfin-server",
    "jellyfin-web": "jellyfin-web",
    "radarr": None,  # not in fedora, but in copr
    "sonarr": None,
    "prowlarr": None,
    "bazarr": None,
    "lidarr": None,
    "readarr": None,
    "pyload-ng": None,
    "streamlink": "streamlink",
    "yt-dlp": "yt-dlp",
    "gallery-dl": "gallery-dl",
    "nicotine+": "nicotine+",
    "neo-matrix": None,  # AUR
    "no-more-secrets": None,  # AUR
    "cbonsai": None,  # not in fedora
    "pipes.sh": None,  # not in fedora
    "genact": None,  # brew
    "bucklespring": None,  # not in fedora
    "cava": "cava",
    "glava": "glava",
    "projectm": "projectM",
    "projectm-pulseaudio": "projectM-pulseaudio",
    "gource": "gource",
    "conky": "conky",
    "polybar": "polybar",
    "i3status": "i3status",
    "i3": "i3",
    "i3-gaps": "i3-gaps",
    "i3-wm": "i3",
    "i3lock": "i3lock",
    "dwm": "dwm",
    "xmonad": "xmonad",
    "qtile": "qtile",
    "bspwm": "bspwm",
    "herbstluftwm": "herbstluftwm",
    "picom": "picom",
    "compton": "picom",
    "xorg": "xorg-x11-server-Xorg",
    "xorg-xinit": "xorg-x11-xinit",
    "xorg-server": "xorg-x11-server-Xorg",
    "xorg-xrandr": "xorg-x11-server-utils",
    "xorg-xinput": "xorg-x11-server-utils",
    "xorg-xset": "xorg-x11-server-utils",
    "xorg-xrdb": "xorg-x11-server-utils",
    "xorg-xdpyinfo": "xorg-x11-utils",
    "xorg-xev": "xorg-x11-utils",
    "xorg-xkill": "xorg-x11-utils",
    "xorg-xprop": "xorg-x11-utils",
    "xorg-xwininfo": "xorg-x11-utils",
    "libinput": "libinput",
    "libwacom": "libwacom",
    "llvm": "llvm",
    "clang": "clang",
    "lld": "lld",
    "lldb": "lldb",
    "compiler-rt": "compiler-rt",
    "mold": "mold",
    "samurai": "samurai",
    "re2c": "re2c",
    "flex": "flex",
    "bison": "bison",
    "m4": "m4",
    "autoconf": "autoconf",
    "automake": "automake",
    "make": "make",
    "cmake": "cmake",
    "meson": "meson",
    "ninja": "ninja-build",
    "pkg-config": "pkgconf-pkg-config",
    "pkgconf": "pkgconf",
    "gcc": "gcc",
    "gcc-c++": "gcc-c++",
    "gfortran": "gcc-gfortran",
    "libtool": "libtool",
    "intltool": "intltool",
    "gettext": "gettext",
    "patch": "patch",
    "diffutils": "diffutils",
    "glibc": "glibc",
    "glib2": "glib2",
    "glibc-devel": "glibc-devel",
    "binutils": "binutils",
    "elfutils": "elfutils",
    "readline": "readline",
    "ncurses": "ncurses",
    "zlib": "zlib",
    "bzip2": "bzip2",
    "xz": "xz",
    "lz4": "lz4",
    "zstd": "zstd",
    "openssl": "openssl",
    "gmp": "gmp",
    "mpfr": "mpfr",
    "mpc": "libmpc",
    "isl": "isl",
    "libffi": "libffi",
    "libxml2": "libxml2",
    "libxslt": "libxslt",
    "expat": "expat",
    "json-c": "json-c",
    "json-glib": "json-glib",
    "libyaml": "libyaml",
    "yaml-cpp": "yaml-cpp",
    "protobuf": "protobuf",
    "protobuf-c": "protobuf-c",
    "grpc": "grpc",
    "flatbuffers": "flatbuffers",
    "msgpack": "msgpack",
    "boost": "boost",
    "tbb": "tbb",
    "eigen3": "eigen3",
    "opencv": "opencv",
    "openblas": "openblas",
    "lapack": "lapack",
    "blas": "blas",
    "fftw": "fftw",
    "gsl": "gsl",
    "nlopt": "NLopt",
    "ceres-solver": "ceres-solver",
    "suitesparse": "suitesparse",
    "arpack": "arpack",
    "superlu": "superlu",
    "hdf5": "hdf5",
    "netcdf": "netcdf",
    "gdal": "gdal",
    "proj": "proj",
    "geos": "geos",
    "poppler": "poppler",
    "poppler-qt5": "poppler-qt5",
    "poppler-qt6": "poppler-qt6",
    "harfbuzz": "harfbuzz",
    "pango": "pango",
    "cairo": "cairo",
    "pixman": "pixman",
    "libpng": "libpng",
    "libjpeg-turbo": "libjpeg-turbo",
    "libtiff": "libtiff",
    "libwebp": "libwebp",
    "giflib": "giflib",
    "jasper": "jasper",
    "openjpeg2": "openjpeg2",
    "lcms2": "lcms2",
    "libraw": "LibRaw",
    "exiv2": "exiv2",
    "SDL2": "SDL2",
    "SDL3": "SDL3",
    "sfml": "SFML",
    "allegro": "allegro5",
    "raylib": "raylib",
    "freeimage": "freeimage",
    "devil": "DevIL",
    "glm": "glm",
    "assimp": "assimp",
    "cglm": None,
    "tinyobjloader": "tinyobjloader",
    "stb": "stb",
    "xxhash": "xxhash",
    "lz4": "lz4",
    "snappy": "snappy",
    "brotli": "brotli",
    "minizip": "minizip",
    "libarchive": "libarchive",
    "dbus": "dbus",
    "systemd": "systemd",
    "elogind": None,  # no elogind in fedora, systemd-logind
    "seatd": "seatd",
    "libseat": "libseat",
    "libinput": "libinput",
    "mtdev": "mtdev",
    "libevdev": "libevdev",
    "libudev0": None,  # part of systemd
    "libgudev": "libgudev",
    "upower": "upower",
    "accountsservice": "accountsservice",
    "colord": "colord",
    "colord-gtk": "colord-gtk",
    "geoclue2": "geoclue2",
    "libgweather": "libgweather",
    "libgepub": "libgepub",
    "libgsf": "libgsf",
    "libgxps": "libgxps",
    "libspectre": "libspectre",
    "libdjvu": "djvulibre",
    "libzmf": "libzmf",
    "libstaroffice": "libstaroffice",
    "libwps": "libwps",
    "libwpd": "libwpd",
    "libwpg": "libwpg",
    "libvisio": "libvisio",
    "libmspub": "libmspub",
    "libcdr": "libcdr",
    "libetonyek": "libetonyek",
    "libfreehand": "libfreehand",
    "libpagemaker": "libpagemaker",
    "libabw": "libabw",
    "libe-book": "libe-book",
    "libqxp": "libqxp",
    "libnumbertext": "libnumbertext",
    "libexttextcat": "libexttextcat",
    "liblangtag": "liblangtag",
    "liborcus": "liborcus",
    "libixion": "libixion",
    "mdds": "mdds",
    "lpsolve": "lpsolve",
    "coin-or-CoinMP": None,
    "coin-or-Cbc": "coin-or-Cbc",
    "coin-or-Cgl": "coin-or-Cgl",
    "coin-or-Clp": "coin-or-Clp",
    "coin-or-Osi": "coin-or-Osi",
    "coin-or-Utils": "coin-or-Utils",
    "mythes": "mythes",
    "hyphen": "hyphen",
    "libstemmer": "libstemmer",
    "icu": "libicu",
    "boost": "boost",
    "fmt": "fmt",
    "spdlog": "spdlog",
    "abseil-cpp": "abseil-cpp",
    "gtest": "gtest",
    "gmock": "gmock",
    "benchmark": "benchmark",
    "catch2": "catch",
    "doctest": "doctest",
    "trompeloeil": None,
    "simdjson": "simdjson",
    "nlohmann-json": "json",
    "tomlplusplus": "tomlplusplus",
    "yaml-cpp": "yaml-cpp",
    "cpp-httplib": "cpp-httplib",
    "cpprestsdk": "cpprest",
    "poco": "poco",
    "qt5-qtbase": "qt5-qtbase",
    "qt6-qtbase": "qt6-qtbase",
    "wxwidgets": "wxGTK",
    "gtkmm3": "gtkmm30",
    "gtkmm4": "gtkmm4.0",
    "libsigc++": "libsigc++20",
    "glibmm": "glibmm24",
    "pangomm": "pangomm",
    "atkmm": "atkmm",
    "cairomm": "cairomm",
    "opensubdiv": "opensubdiv",
    "embree": "embree",
    "oidn": "oidn",
    "openimagedenoise": "oidn",
    "openvdb": "openvdb",
    "alembic": "alembic",
    "ptex": "ptex",
    "openexr": "openexr",
    "ilmbase": "openexr",
    "openimageio": "OpenImageIO",
    "opencolorio": "OpenColorIO",
    "openshadinglanguage": "OpenShadingLanguage",
    "osl": "OpenShadingLanguage",
    "partio": "partio",
    "seexpr": "seexpr",
    "usd": None,  # Universal Scene Description
    "materialx": "MaterialX",
    "draco": "draco",
    "meshoptimizer": "meshoptimizer",
    "volk": "volk",
    "volk-tools": None,
    "vulkan-loader": "vulkan-loader",
    "vulkan-validation-layers": "vulkan-validation-layers",
    "glslang": "glslang",
    "shaderc": "shaderc",
    "spirv-tools": "spirv-tools",
    "spirv-headers": "spirv-headers",
    "spirv-cross": "spirv-cross",
    "spirv-llvm-translator": "spirv-llvm-translator",
    "libplacebo": "libplacebo",
    "libavif": "libavif",
    "libjxl": "libjxl",
    "rav1e": "rav1e",
    "svt-av1": "svt-av1",
    "dav1d": "dav1d",
    "aom": "libaom",
    "x264": "x264",
    "x265": "x265",
    "xvidcore": "xvidcore",
    "libmpeg2": None,
    "libvpx": "libvpx",
    "libtheora": "libtheora",
    "lame": "lame",
    "twolame": "twolame",
    "opencore-amr": "opencore-amr",
    "vo-amrwbenc": "vo-amrwbenc",
    "speex": "speex",
    "opus": "opus",
    "vorbis-tools": "vorbis-tools",
    "flac": "flac",
    "wavpack": "wavpack",
    "libsndfile": "libsndfile",
    "libsamplerate": "libsamplerate",
    "portaudio": "portaudio",
    "portmidi": "portmidi",
    "fluidsynth": "fluidsynth",
    "soundtouch": "soundtouch",
    "rubberband": "rubberband",
    "libmysofa": "libmysofa",
    "pipewire": "pipewire",
    "pipewire-jack": "pipewire-jack-audio-connection-kit",
    "pipewire-pulse": "pipewire-pulseaudio",
    "pipewire-alsa": "pipewire-alsa",
    "wireplumber": "wireplumber",
    "helvum": "helvum",
    "qpwgraph": "qpwgraph",
    "carla": "carla",
    "ardour6": "ardour7",
    "audacity": "audacity",
    "reaper": None,
    "bitwig-studio": None,
    "lmms": "lmms",
    "muse": "musescore",
    "rosegarden": "rosegarden",
    "hydrogen": "hydrogen",
    "guitarix": "guitarix",
    "rakarrack": "rakarrack",
    "calf": "calf",
    "lsp-plugins": "lsp-plugins",
    "zam-plugins": None,
    "x42-plugins": None,
    "dragonfly-reverb": None,
    "geonkick": "geonkick",
    "avldrums": None,
    "helm": "helm",
    "vitalium": None,
    "surge-xt": None,
    "dexed": None,
    "odin2": None,
    "yoshimi": "yoshimi",
    "zynaddsubfx": "zynaddsubfx",
    "amsynth": "amsynth",
    "setbfree": "setbfree",
    "bristol": None,
    "whysynth": None,
    "phasex": None,
    "ams": None,
    "jack_mixer": None,
    "non-mixer": "non-mixer",
    "non-session-manager": "non-session-manager",
    "non-timeline": "non-timeline",
    "patchage": "patchage",
    "aj-snapshot": None,
    "jack-rack": None,
    "ray-session": None,  # AUR
    "songrec": None,
    "shazam-client": None,
    "picard": "picard",
    "whipper": None,
    "abcde": "abcde",
    "rubyripper": None,
    "asunder": "asunder",
    "sound-juicer": "sound-juicer",
    "soundconverter": "soundconverter",
    "rhythmbox": "rhythmbox",
    "banshee": None,
    "quodlibet": "quodlibet",
    "exfalso": "quodlibet",
    "deadbeef": "deadbeef",
    "audacious": "audacious",
    "gmusicbrowser": None,
    "strawberry": "strawberry",
    "clementine": "clementine",
    "sayonara": "sayonara",
    "elisa": None,  # part of plasma
    "cantata": "cantata",
    "ncmpcpp": "ncmpcpp",
    "cmus": "cmus",
    "moc": "moc",
    "gpodder": "gpodder",
    "yarock": None,
    "taoup": None,  # AUR / custom
    "richcolors": None,  # custom pkg
    "albumdetails": None,  # custom pkg
    "proxypilot": None,  # custom pkg
    "ssh-to-age": None,  # custom pkg / AUR
    "sidecar": None,  # custom
    "throne": None,  # custom
    "tailray": None,  # custom
    "neg-pretty-printer": None,  # custom
    "duf": "duf",
    "wl": None,  # custom AUR
    "raise": None,  # custom
    "nvpy": None,
    "simplenote": None,
    "zim": "zim",
    "trilium": None,
    "obsidian": None,
    "logseq": None,
    "joplin": "joplin",
    "standardnotes": None,
    "boostnote": None,
    "notable": None,
    "typora": None,
    "marktext": None,
    "ghostwriter": "ghostwriter",
    "apostrophe": "apostrophe",
    "retext": "retext",
    "featherpad": "featherpad",
    "notepadqq": None,
    "mousepad": "mousepad",
    "leafpad": "leafpad",
    "gedit": "gedit",
    "gedit-plugins": "gedit-plugins",
    "xed": "xed",
    "pluma": "pluma",
    "geany": "geany",
    "geany-plugins": "geany-plugins",
    "scite": "scite",
    "emacs": "emacs",
    "spacemacs": None,
    "doom-emacs": None,
    "vim": "vim",
    "neovim": "neovim",
    "helix": "helix",
    "kakoune": "kakoune",
    "micro": "micro",
    "nano": "nano",
    "joe": "joe",
    "mcedit": "mc",
    "tilde": "tilde",
    "amp": None,
    "amp-bin": None,
    "xi-editor": None,
    "vis": None,
    "slap": None,
    "dte": None,
    "orbital": None,
    "pyvim": None,
    "bpython": "bpython",
    "ptpython": "ptpython",
    "ipython": "ipython",
    "jupyterlab": "jupyterlab",
    "jupyter-notebook": "notebook",
    "jupyterlab-lsp": None,
    "jupyter-nbclassic": None,
    "glow": "glow",
    "mdcat": "mdcat",
    "bat": "bat",
    "rich-cli": None,
    "mdless": None,
    "hoedown": None,
    "cmake-language-server": None,  # AUR
    "clangd": None,  # part of clang-tools-extra
    "marksman": "marksman",
    "vale": "vale",
    "writegood": None,
    "proselint": "proselint",
    "alex": None,
    "redpen": None,
    "textlint": None,
    "deno": "deno",
    "bun": None,
    "bun-js": None,
    "pnpm": "pnpm",
    "yarn": "yarnpkg",
    "act": None,  # AUR
    "act-bin": None,  # AUR
    "gh": "gh",
    "glab": "glab",
    "hub": "hub",
    "lab": None,
    "tea": None,
    "broot": "broot",
    "lsd": "lsd",
    "exa": "exa",  # deprecated but eza is modern
    "eza": "eza",
    "fd": "fd-find",
    "ripgrep": "ripgrep",
    "ugrep": "ugrep",
    "ag": "the_silver_searcher",
    "pt": None,
    "sift": None,
    "selecta": None,
    "skim": "skim",
    "fzf": "fzf",
    "peco": "peco",
    "percol": None,
    "fzy": "fzy",
    "sentaku": None,
    "z": "zoxide",
    "zoxide": "zoxide",
    "autojump": "autojump",
    "fasd": None,
    "enhancd": None,
    "direnv": "direnv",
    "asdf": None,
    "rtx": None,  # now mise
    "mise": "mise",
    "vfox": None,
    "proto": None,
    "mprocs": "mprocs",
    "overmind": None,
    "foreman": None,
    "hivemind": None,
    "concurrently": None,
    "watchexec": "watchexec",
    "cargo-watch": None,
    "nodemon": None,
    "air": None,
    "just": "just",
    "make": "make",
    "ninja": "ninja-build",
    "task": "task",
    "mimic": None,
    "makesure": None,
    "run": None,
    "rover": None,
    "mask": None,
    "mmake": None,
    "sake": None,
    "go-task": "task",
    "tokei": "tokei",
    "loc": None,
    "cloc": "cloc",
    "scc": None,  # brew
    "gocloc": None,
    "loccount": None,
    "polyglot": None,
    "sloccount": "sloccount",
    "ohcount": None,
    "git": "git",
    "jj": "jj",
    "fossil": "fossil",
    "hg": "mercurial",
    "mercurial": "mercurial",
    "subversion": "subversion",
    "cvs": "cvs",
    "rcs": "rcs",
    "darcs": "darcs",
    "pijul": None,
    "breezy": "breezy",
    "git-absorb": None,
    "git-branchless": None,
    "git-cinnabar": None,
    "git-revise": None,
    "git-imerge": None,
    "git-stack": None,
    "git-flight-rules": None,
    "git-secret": "git-secret",
    "git-crypt": "git-crypt",
    "git-lfs": "git-lfs",
    "git-annex": "git-annex",
    "transcrypt": None,
    "blackbox": None,
    "sops": "sops",
    "vals": None,
    "helm-secrets": None,
    "sealed-secrets": None,
    "external-secrets": None,
    "vault": "vault",
    "consul": "consul",
    "nomad": None,
    "terraform": "terraform",
    "terragrunt": "terragrunt",
    "pulumi": "pulumi",
    "tofu": None,  # opentofu
    "ansible": "ansible",
    "ansible-lint": "ansible-lint",
    "ansible-core": "ansible-core",
    "salt": "salt",
    "salt-minion": "salt-minion",
    "salt-master": "salt-master",
    "salt-api": None,
    "salt-cloud": None,
    "salt-ssh": "salt-ssh",
    "chef": None,
    "puppet": "puppet",
    "fabric": "fabric",
    "invoke": "python3-invoke",
    "paramiko": "python3-paramiko",
    "kitchen": None,
    "test-kitchen": None,
    "molecule": None,
    "vagrant": "vagrant",
    "packer": "packer",
    "docker-compose": "docker-compose",
    "podman-compose": "podman-compose",
    "nerdctl": None,  # brew
    "buildah": "buildah",
    "skopeo": "skopeo",
    "podman": "podman",
    "docker": "moby-engine",  # docker ce
    "docker-buildx": None,
    "docker-compose": "docker-compose",
    "containerd": "containerd",
    "runc": "runc",
    "crun": "crun",
    "youki": None,
    "kaniko": None,
    "buildkit": None,
    "finch": None,
    "rancher-desktop": None,
    "colima": None,
    "lima": "lima",
    "podman-desktop": "podman-desktop",
    "flathub": "flatpak",
    "snapd": None,
    "appimagelauncher": "appimagelauncher",
    "distrobox": "distrobox",
    "toolbox": "toolbox",
    "devbox": None,
    "devenv": None,
    "nix": None,
    "home-manager": None,
    "nixpkgs": None,
    "nix-flakes": None,
    "chezmoi": "chezmoi",
    "yadm": "yadm",
    "dotbot": None,
    "dotdrop": None,
    "rcm": "rcm",
    "homeshick": None,
    "homesick": None,
    "stow": "stow",
    "dotter": None,
    "comtrya": None,
    "bisync": None,
    "unison": "unison",
    "syncthing": "syncthing",
    "resilio-sync": None,
    "nextcloud-client": "nextcloud-client",
    "owncloud-client": "owncloud-client",
    "dropbox": "dropbox",
    "megasync": "megasync",
    "insync": None,
    "rclone": "rclone",
    "b2sum": None,
    "par2cmdline": "par2cmdline",
    "xorriso": "xorriso",
    "cdrkit": "wodim",
    "dvd+rw-tools": "dvd+rw-tools",
    "libburn": "libburn",
    "libisofs": "libisofs",
    "libisoburn": "libisoburn",
    "udftools": "udftools",
    "file": "file",
    "expect": "expect",
    "telnet": "telnet",
    "rdesktop": "rdesktop",
    "freerdp": "freerdp",
    "remmina": "remmina",
    "vinagre": "vinagre",
    "krfb": "krfb",
    "x2goclient": "x2goclient",
    "tmate": "tmate",
    "byobu": "byobu",
    "screen": "screen",
    "tmux": "tmux",
    "zellij": "zellij",
    "mosh": "mosh",
    "et": None,
    "trzsz": None,
    "trzsz-go": None,
    "trzsz-ssh": None,
    "zssh": None,
    "lrzsz": "lrzsz",
    "openssh": "openssh",
    "dropbear": "dropbear",
    "tinyssh": None,
    "sslh": "sslh",
    "haproxy": "haproxy",
    "nginx": "nginx",
    "apache": "httpd",
    "caddy": "caddy",
    "traefik": None,
    "envoy": None,
    "linkerd": None,
    "istio": None,
    "consul": "consul",
    "etcd": "etcd",
    "zookeeper": "zookeeper",
    "kafka": None,
    "rabbitmq-server": "rabbitmq-server",
    "redis": "redis",
    "valkey": "valkey",
    "memcached": "memcached",
    "mariadb": "mariadb",
    "mysql": "community-mysql",
    "percona-server": None,
    "postgresql": "postgresql",
    "sqlite": "sqlite",
    "timescaledb": None,
    "cockroachdb": "cockroach",
    "yugabytedb": None,
    "scylladb": None,
    "cassandra": None,
    "mongodb": "mongodb",
    "mongosh": None,
    "couchdb": None,
    "rethinkdb": None,
    "arangodb": "arangodb3",
    "neo4j": "neo4j",
    "dgraph": None,
    "surreal": None,
    "meilisearch": "meilisearch",
    "typesense": None,
    "elasticsearch": None,
    "opensearch": None,
    "kibana": None,
    "logstash": None,
    "fluentd": None,
    "fluent-bit": "fluent-bit",
    "vector": None,
    "grafana": "grafana",
    "prometheus": "prometheus",
    "alertmanager": None,
    "thanos": None,
    "cortex": None,
    "mimir": None,
    "loki": "loki",
    "tempo": None,
    "jaeger": "jaeger",
    "opentelemetry": None,
    "parca": None,
    "pyroscope": None,
    "netdata": "netdata",
    "glances": "glances",
    "cockpit": "cockpit",
    "webmin": None,
    "zabbix": None,
    "nagios": None,
    "icinga2": "icinga2",
    "sensu": None,
    "check_mk": None,
    "monit": "monit",
    "supervisor": "supervisor",
    "s6": "s6",
    "runit": "runit",
    "openrc": None,
    "dinit": "dinit",
    "shepherd": None,
    "nosy": None,
    "perp": None,
    "daemontools": "daemontools",
    "daemontools-encore": None,
    "minit": None,
    "finit": None,
    "procd": None,
    "busybox": "busybox",
    "toybox": "toybox",
    "coreutils": "coreutils",
    "findutils": "findutils",
    "gawk": "gawk",
    "sed": "sed",
    "grep": "grep",
    "tar": "tar",
    "gzip": "gzip",
    "bzip2": "bzip2",
    "xz": "xz",
    "less": "less",
    "which": "which",
    "man-db": "man-db",
    "man-pages": "man-pages",
    "info": "info",
    "texinfo": "texinfo",
    "os-prober": "os-prober",
    "grub": "grub2",
    "grub-btrfs": "grub2-btrfs",
    "limine": None,  # not in fedora
    "systemd-boot": "systemd-boot",
    "efibootmgr": "efibootmgr",
    "efivar": "efivar",
    "refind": "refind",
    "Clover": None,
    "OpenCore": None,
    "lilo": None,
    "linux-zen": None,  # Fedora-specific kernel
    "linux-cachyos": None,  # CachyOS kernel
    "linux-cachyos-headers": None,  # CachyOS kernel headers
    "linux-lts": None,  # Fedora long-term kernel
    "linux-rt": None,  # Fedora real-time kernel
    "linux-rt-lts": None,
    "linux-hardened": None,
    "linux-clear": None,
    "linux-xanmod": None,
    "linux-amd": None,
    "linux-surface": None,
    "linux-firmware": "linux-firmware",
    "amd-ucode": "amd-ucode-firmware",
    "intel-ucode": "microcode_ctl",
    "nvidia": "nvidia-gpu-firmware",
    "nvidia-dkms": None,
    "nvidia-open": "kmod-nvidia-open",
    "nvidia-utils": "nvidia-gpu-firmware",
    "nvidia-settings": "nvidia-settings",
    "cuda": None,  # not in fedora, use nvidia repo
    "cudnn": None,
    "tensorrt": None,
    "nccl": None,
    "rocm": "rocm",
    "rocm-opencl": "rocm-clinfo",
    "rocm-hip": "rocm-hip",
    "rocm-hip-runtime": "rocm-hip-devel",
    "miopen": "miopen",
    "miopen-hip": "miopen-hip",
    "rccl": "rccl",
    "mivisionx": None,
    "mlirmlir": None,
    "onnxruntime": "onnxruntime",
    "onnxruntime-rocm": "onnxruntime-rocm",
    "openvino": "openvino",
    "opencl": "opencl-headers",
    "clinfo": "clinfo",
    "ocl-icd": "ocl-icd",
    "pocl": "pocl",
    "intel-compute-runtime": "intel-compute-runtime",
    "rocm-opencl-runtime": "rocm-clinfo",
    "mesa": "mesa",
    "mesa-libgl": "mesa-libGL",
    "mesa-vulkan": "mesa-vulkan-drivers",
    "mesa-va": "mesa-va-drivers",
    "mesa-vdpau": "mesa-vdpau-drivers",
    "vulkan": "vulkan-loader",
    "vulkan-tools": "vulkan-tools",
    "vulkan-validation": "vulkan-validation-layers",
    "vulkan-mesa": "vulkan-loader",  # mesa vulkan is included
    "amdvlk": "amdvlk",
    "amdvlk-bin": "amdvlk",
    "vulkan-radeon": "mesa-vulkan-drivers",
    "libva": "libva",
    "libva-utils": "libva-utils",
    "intel-media-driver": "intel-media-driver",
    "intel-media-sdk": "intel-mediasdk",
    "intel-gmmlib": "intel-gmmlib",
    "intel-opencl": "intel-compute-runtime",
    "intel-igc": "intel-igc",
    "intel-graphics-compiler": "intel-igc",
    "intel-level-zero": "intel-level-zero",
    "intel-level-zero-gpu": "intel-level-zero-gpu",
    "level-zero": "intel-level-zero",
    "oneapi": None,
    "dpcpp": None,
    "intel-ipp": None,
    "intel-mkl": None,
    "intel-tbb": "tbb",
    "intel-daal": None,
    "mkinitcpio": None,  # Arch-specific initramfs
    "dracut": "dracut",
    "booster": None,
    "initramfs": None,
    "plymouth": "plymouth",
    "systemd-zram": "zram-generator",
    "uwsm": "uwsm",
    "xwaylandvideobridge": "xwaylandvideobridge",
    "xwayland-satellite": None,
    "xwayland-run": None,
    "kwin": "kwin",
    "kwin-wayland": "kwin-wayland",
    "mutter": "mutter",
    "weston": "weston",
    "sway": "sway",
    "river": "river",
    "hyprland-qtutils": "hyprland-qtutils",
    "hyprland-protocols": "hyprland-protocols",
    "aquamarine": "aquamarine",
    "hyprcursor": "hyprcursor",
    "hyprgraphics": None,
    "hyprlang": "hyprlang",
    "hyprutils": "hyprutils",
    "hyprwayland-scanner": "hyprwayland-scanner",
    "hyprland-idle": "hypridle",
    "hyprland-lock": "hyprlock",
    "hyprland-picker": "hyprpicker",
    "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
    "niri": "niri",
    "cosmic-comp": None,  # COSMIC
    "cosmic-greeter": None,
    "cosmic-session": None,
    "cosmic-files": None,
    "cosmic-edit": None,
    "cosmic-terminal": None,
    "cosmic-store": None,
    "cosmic-settings": None,
    "cosmic-launcher": None,
    "cosmic-applets": None,
    "cosmic-app-library": None,
    "cosmic-bg": None,
    "cosmic-idle": None,
    "cosmic-notifications": None,
    "cosmic-osd": None,
    "cosmic-panel": None,
    "cosmic-randr": None,
    "cosmic-screenshot": None,
    "cosmic-workspaces": None,
    "cosmic-player": None,
    "pixora-icons": None,  # custom icon theme
    "pixora-icons-git": None,  # AUR
    "bottles": "bottles",
    "heroic": "heroic-games-launcher",
    "legendary": "legendary",
    "compat_golang": None,
    "miniupnpc": "miniupnpc",
    "miniupnpd": "miniupnpd",
    "natpmp": None,
    "natpmpc": "libnatpmp",
    "natmap": None,
    "coturn": "coturn",
    "stun": "stuntman",
    "stunnel": "stunnel",
    "sniproxy": None,
    "obfs4proxy": "obfs4",
    "shadowsocks": "shadowsocks-libev",
    "shadowsocks-rust": "shadowsocks-rust",
    "v2ray": "v2ray",
    "v2raya": None,  # AUR
    "v2rayn": None,  # AUR
    "sing-box": "sing-box",
    "xray": None,
    "xray-core": None,
    "hiddify": None,
    "hiddify-core": None,
    "nekoray": None,
    "nekobox": None,
    "clash": None,
    "clash-meta": None,
    "clash-verge": None,
    "clash-nyanpasu": None,
    "flclash": None,  # AUR
    "flclashx-bin": None,  # AUR
    "amneziawg": None,  # AUR
    "amneziawg-dkms": None,  # AUR
    "amneziawg-tools": None,  # AUR
    "proton-vpn-cli": None,
    "proton-vpn-gui": None,
    "proton-vpn-gtk": None,
    "mullvad": None,
    "mullvad-vpn": None,
    "tailscale": "tailscale",
    "zerotier": "zerotier-one",
    "nebula": "nebula",
    "boringtun": None,
    "wireguard-tools": "wireguard-tools",
    "wireguard-go": None,
    "strongswan": "strongswan",
    "libreswan": "libreswan",
    "openvpn": "openvpn",
    "openswan": None,
    "softether": None,
    "tinc": "tinc",
    "tinc-vpn": "tinc",
    "fastd": "fastd",
    "l2tp": "xl2tpd",
    "ppp": "ppp",
    "pptp-client": "pptp",
    "xl2tpd": "xl2tpd",
    "tor": "tor",
    "torsocks": "torsocks",
    "nyx": "nyx",
    "privoxy": "privoxy",
    "squid": "squid",
    "tinyproxy": "tinyproxy",
    "polipo": None,
    "mitmproxy": "mitmproxy",
    "charles": None,
    "burpsuite": None,
    "zap": None,
    "wireshark": "wireshark",
    "wireshark-qt": "wireshark",
    "tshark": "wireshark-cli",
    "tcpdump": "tcpdump",
    "ngrep": "ngrep",
    "tcpflow": "tcpflow",
    "tcpreplay": "tcpreplay",
    "tcptrace": "tcptrace",
    "arp-scan": "arp-scan",
    "arping": "arping",
    "nping": "nmap",
    "hping": "hping3",
    "fping": "fping",
    "tcping": None,
    "httping": "httping",
    "dnstracer": "dnstracer",
    "dnsdiag": None,
    "dnstop": "dnstop",
    "dnsperf": None,
    "flamethrower": None,
    "wrk": "wrk",
    "wrk2": None,
    "ab": "httpd-tools",
    "siege": "siege",
    "hey": None,
    "vegeta": None,
    "drill": "ldns",
    "ldns": "ldns",
    "bind": "bind",
    "bind-utils": "bind-utils",
    "pdns": "pdns",
    "pdns-recursor": "pdns-recursor",
    "dnsmasq": "dnsmasq",
    "unbound": "unbound",
    "adguardhome": "adguardhome",
    "pi-hole": None,
    "technitium": None,
    "dnsdist": "dnsdist",
    "knot": "knot",
    "knot-resolver": "knot-resolver",
    "nsd": "nsd",
    "coredns": None,
    "filebrowser": "filebrowser",
    "filed": None,
    "dufs": "dufs",
    "miniserve": "miniserve",
    "darkhttpd": "darkhttpd",
    "lighttpd": "lighttpd",
    "micro-httpd": None,
    "mongoose": None,
    "libmicrohttpd": "libmicrohttpd",
    "onion": None,
    "festival": "festival",
    "mary-tts": None,
    "open-jtalk": "OpenJTalk",
    "hts-engine": None,
    "htsvoice": None,
    "flite": "flite",
    "svox-pico": None,
    "espeak": "espeak",
    "espeak-ng": "espeak-ng",
    "mbrola": None,
    "piper": "piper",
    "piper-tts": "piper",
    "whisper": None,
    "whisper-cpp": "whisper-cpp",
    "faster-whisper": None,
    "coqui-tts": None,
    "tortoise-tts": None,
    "styletts2": None,
    "bark": None,
    "vall-e": None,
    "elevenlabs": None,
    "play-ht": None,
    "openai-tts": None,
    "azure-tts": None,
    "gcloud-tts": None,
    "aws-polly": None,
    "ibm-watson": None,
    "rhvoice": None,
    "mary": None,
    "openai-whisper": None,
    "whisper.cpp": "whisper-cpp",
    "hermes": None,
    "hermes-agent": None,  # AUR
    "ollama-vulkan": None,  # custom
    "bazecor": None,  # AUR
    "paru": None,  # AUR helper, not needed on Fedora
    "paru-debug": None,  # AUR helper debug
    "yay": None,  # AUR helper, not needed on Fedora
    "pacman": "dnf",  # fundamentally different
    "dnf": "dnf",
    "rpm": "rpm",
    "rpm-ostree": "rpm-ostree",
    "flatpak": "flatpak",
    "snapd": None,
    "apk": None,
    "dpkg": None,
    "slirp4netns": "slirp4netns",
    "passt": "passt",
    "aardvark-dns": "aardvark-dns",
    "netavark": "netavark",
    "catatonit": "catatonit",
    "conmon": "conmon",
    "crun": "crun",
    "fuse-overlayfs": "fuse-overlayfs",
    "slirp4netns": "slirp4netns",
    "containers-common": "containers-common",
    "shadow-utils": "shadow-utils",
    "criu": "criu",
    "libseccomp": "libseccomp",
    "gvisor": None,
    "kata-containers": None,
    "firecracker": None,
    "qemu": "qemu",
    "libvirt": "libvirt",
    "libvirt-daemon": "libvirt-daemon",
    "virt-install": "virt-install",
    "virt-manager": "virt-manager",
    "virt-viewer": "virt-viewer",
    "looking-glass": None,
    "quickemu": "quickemu",
    "quickgui": "quickgui",
    "swtpm": "swtpm",
    "edk2-ovmf": "edk2-ovmf",
    "edk2-aarch64": "edk2-aarch64",
    "seabios": "seabios",
    "ipxe": "ipxe",
    "sgabios": "sgabios",
    "openjdk": "java-21-openjdk",
    "openjdk11": "java-11-openjdk",
    "openjdk17": "java-17-openjdk",
    "openjdk21": "java-21-openjdk",
    "openjdk8": "java-1.8.0-openjdk",
    "graalvm": "graalvm",
    "temurin": None,
    "corretto": None,
    "zulu": None,
    "adoptium": None,
    "liberica": None,
    "semeru": None,
    "dragonwell": None,
    "kona": None,
    "bi-sheng": None,
    "java": "java-21-openjdk",
    "jre": "java-21-openjdk",
    "jdk": "java-21-openjdk-devel",
    "maven": "maven",
    "gradle": "gradle",
    "ant": "ant",
    "sbt": "sbt",
    "scala": "scala",
    "scala3": "scala3",
    "mill": None,
    "bazel": "bazel",
    "buck2": None,
    "please": None,
    "pants": None,
    "blade": None,
    "ninja": "ninja-build",
    "meson": "meson",
    "cmake": "cmake",
    "qmake": "qt5-qtbase-devel",
    "xmake": "xmake",
    "premake": "premake",
    "scons": "scons",
    "waf": None,
    "jam": "jam",
    "bjam": "boost-jam",
    "gn": None,
    "gyb": None,
    "gyp": None,
    "ninja": "ninja-build",
    "samurai": "samurai",
    "tup": "tup",
    "redo": "redo",
    "shake": None,
    "bazel": "bazel",
    "pantsbuild": None,
    "recc": None,
    "icecream": "icecream",
    "distcc": "distcc",
    "ccache": "ccache",
    "sccache": "sccache",
    "buildcache": None,
    "stcache": None,
    "mold": "mold",
    "lld": "lld",
    "gold": "binutils-gold",
    "m4": "m4",
    "autoconf": "autoconf",
    "automake": "automake",
    "libtool": "libtool",
    "pkg-config": "pkgconf-pkg-config",
    "pkgconf": "pkgconf",
    "make": "make",
    "gmake": "make",
    "pmake": None,
    "bmake": None,
    "cmake": "cmake",
    "ninja": "ninja-build",
    "meson": "meson",
    "gn": None,
    "vcpkg": "vcpkg",
    "conan": "conan",
    "xrepo": None,
    "hunter": None,
    "cget": None,
    "cpm": None,
    "poac": None,
    "cargo": "cargo",
    "rustc": "rust",
    "rust": "rust",
    "rust-src": "rust-src",
    "rust-analyzer": "rust-analyzer",
    "rustfmt": "rustfmt",
    "clippy": "clippy",
    "cargo-audit": "cargo-audit",
    "cargo-bloat": "cargo-bloat",
    "cargo-crev": None,
    "cargo-deny": "cargo-deny",
    "cargo-edit": "cargo-edit",
    "cargo-expand": "cargo-expand",
    "cargo-flamegraph": None,
    "cargo-fuzz": None,
    "cargo-geiger": None,
    "cargo-generate": "cargo-generate",
    "cargo-hack": "cargo-hack",
    "cargo-llvm-cov": "cargo-llvm-cov",
    "cargo-make": "cargo-make",
    "cargo-msrv": None,
    "cargo-nextest": "cargo-nextest",
    "cargo-outdated": "cargo-outdated",
    "cargo-release": None,
    "cargo-sort": None,
    "cargo-tarpaulin": "cargo-tarpaulin",
    "cargo-udeps": "cargo-udeps",
    "cargo-update": None,
    "cargo-watch": "cargo-watch",
    "cargo-wizard": None,
    "cargo-xwin": None,
    "cargo-zigbuild": None,
    "bacon": "bacon",
    "rustic": None,
    "du-dust": "dust",
    "lsd": "lsd",
    "delta": "git-delta",
    "difftastic": "difftastic",
    "dysk": "dysk",
    "procs": "procs",
    "bat": "bat",
    "exa": "exa",
    "eza": "eza",
    "fd-find": "fd-find",
    "ripgrep": "ripgrep",
    "tokei": "tokei",
    "hyperfine": "hyperfine",
    "xh": "xh",
    "xcp": None,
    "xcompress": None,
    "ouch": "ouch",
    "dtrx": None,
    "unarchiver": None,
    "patool": None,
    "czkawka": None,
    "dupe-krill": None,
    "ffsend": None,
    "wormhole": None,
    "magic-wormhole": "magic-wormhole",
    "croc": "croc",
    "syncthing": "syncthing",
    "rclone": "rclone",
    "restic": "restic",
    "rustic": None,
    "kopia": "kopia",
    "alive2": None,
    "alkis": None,
    "amp": None,
    "arthroprod": None,
    "ascii": None,
    "astra": None,
    "atsamd": None,
    "auto-cpufreq": None,
    "autoconf": "autoconf",
    "b3sum": None,
    "bandwhich": "bandwhich",
    "bangle": None,
    "banner": None,
    "base16384": None,
    "bat": "bat",
    "bkt": None,
    "blue-recorder": None,
    "bob-nvim": None,
    "bolt": None,
    "bonnie++": "bonnie++",
    "boom": None,
    "bore": None,
    "bottom": "bottom",
    "bpf-linker": None,
    "bpf-tools": None,
    "bridge": None,
    "broot": "broot",
    "btd": None,
    "btm": "bottom",
    "btop": "btop",
    "btrfs": None,
    "bubble": None,
    "buffy": None,
    "buildx": None,
    "byt": None,
    "c2patool": None,
    "cachix": None,
    "cargo-binstall": "cargo-binstall",
    "cargo-bundle": None,
    "cargo-c": "cargo-c",
    "cargo-chef": None,
    "cargo-cyclonedx": None,
    "cargo-dist": None,
    "cargo-edit": "cargo-edit",
    "cargo-equip": None,
    "cargo-feature": None,
    "cargo-hack": "cargo-hack",
    "cargo-info": None,
    "cargo-limit": None,
    "cargo-make": "cargo-make",
    "cargo-modules": None,
    "cargo-mutants": None,
    "cargo-ndk": None,
    "cargo-outdated": "cargo-outdated",
    "cargo-pgo": None,
    "cargo-semver-checks": "cargo-semver-checks",
    "cargo-show-asm": None,
    "cargo-spellcheck": None,
    "cargo-supply-chain": None,
    "cargo-sweep": None,
    "cargo-tally": None,
    "cargo-tarpaulin": "cargo-tarpaulin",
    "cargo-udeps": "cargo-udeps",
    "cargo-unused-features": None,
    "cargo-update": None,
    "cargo-vcpkg": None,
    "cargo-vet": None,
    "cargo-watch": "cargo-watch",
    "cargo-wifi": None,
    "cargo-workspaces": None,
    "cargo-xcode": None,
    "catgirl": None,
    "cbindgen": "cbindgen",
    "cc-rs": None,
    "ccl": None,
    "chit": None,
    "clair": None,
    "clipboard-utils": None,
    "clipcat": None,
    "cliphist": "cliphist",
    "cloud-hypervisor": None,
    "cmus-rust": None,
    "cocogitto": "cocogitto",
    "codespan": None,
    "colorizer": None,
    "complate": None,
    "comtrya": None,
    "config-merge": None,
    "confindent": None,
    "conserve": None,
    "contour": "contour-terminal",
    "convco": None,
    "copycat": None,
    "coreutils": None,  # using GNU coreutils
    "cosmic-epoch-system76": None,
    "cotp": "cotp",
    "cpc": None,
    "craft": None,
    "crater": None,
    "crescent": None,
    "criterion": None,
    "critcmp": None,
    "cross": "cross",
    "crow": None,
    "crowbar": None,
    "crowdsec": "crowdsec",
    "crud": None,
    "crunch": None,
    "crypt": None,
    "cryptsetup": "cryptsetup",
    "csc": None,
    "csplit": None,
    "csv": None,
    "csvlens": "csvlens",
    "cursive": None,
    "curve25519": None,
    "cxxbridge": None,
    "cyclonedx": None,
    "czkawka": None,
    "daktilo": None,
    "dalvik": None,
    "damask": None,
    "darklua": None,
    "dash": "dash",
    "databend": None,
    "datafusion": None,
    "dav1d": "dav1d",
    "dbus": None,
    "ddh": None,
    "decompress": None,
    "deepspeech": None,
    "deku": None,
    "delta": "git-delta",
    "deno": "deno",
    "desed": None,
    "desktop-entry-utils": None,
    "det": None,
    "devour": None,
    "dfrs": None,
    "dhat": None,
    "dialog": "dialog",
    "dic": None,
    "diesel": "diesel",
    "difftastic": "difftastic",
    "digga": None,
    "dijo": None,
    "dioxus": None,
    "dirble": None,
    "discover": None,
    "disdvi": None,
    "disk-utils": None,
    "diskfetch": None,
    "diskover": None,
    "diskonaut": "diskonaut",
    "display": None,
    "display3d": None,
    "dissimilar": None,
    "distinst": None,
    "dm": None,
    "dmarc": None,
    "dmg": None,
    "dns-lookup": None,
    "dns-probe": None,
    "dnsname": None,
    "dnsperf": None,
    "dnstake": None,
    "docuum": None,
    "dog": "doggo",
    "doge": None,
    "doggo": "doggo",
    "domain": None,
    "donkey": None,
    "dory": None,
    "dot": None,
    "dots": None,
    "doublecmd": None,
    "dprint": "dprint",
    "dps": None,
    "dpt": None,
    "dragon": None,
    "dragonfly": None,
    "dragoon": None,
    "drawille": None,
    "drift": None,
    "drill": "drill",
    "drm": None,
    "dropbear": "dropbear",
    "drp": None,
    "druid": None,
    "ds": None,
    "dsi": None,
    "dsp": None,
    "dssim": "dssim",
    "dt": None,
    "dte": None,
    "duckscript": None,
    "duo": None,
    "dura": None,
    "dust": "dust",
    "dutree": None,
    "dvm": None,
    "dwarf": None,
    "dwdiff": "dwdiff",
    "dwm": "dwm",
    "dx": None,
    "dye": None,
    "dynamic": None,
    "dysk": "dysk",
    "dyson": None,
    "easyjack": None,
    "eat": None,
    "echinus": None,
    "eddie": None,
    "edge": None,
    "editor": None,
    "edma": None,
    "eep": None,
    "efi": None,
    "egui": None,
    "eiga": None,
    "eject": "eject",
    "eks": None,
    "electric": None,
    "electron": "electron",
    "elkowar": None,
    "elm": "elm",
    "elm-format": None,
    "elysium": None,
    "emacs": "emacs",
    "emplace": None,
    "empty": None,
    "ems": None,
    "enco": None,
    "encoding": None,
    "endbasic": None,
    "enet": None,
    "eng": None,
    "engine": None,
    "enigma": "enigma",
    "enola": None,
    "enscript": "enscript",
    "ent": "ent",
    "entropy": None,
    "enum": None,
    "envhub": None,
    "envio": None,
    "envy": None,
    "eow": None,
    "epage": None,
    "epi": None,
    "epoxy": None,
    "eq": None,
    "erbium": None,
    "erg": "erg",
    "erlang": "erlang",
    "errare": None,
    "error": None,
    "ersatz": None,
    "ersa": None,
    "eru": None,
    "es": None,
    "esbuild": None,
    "esc": None,
    "ese": None,
    "esh": None,
    "eshell": None,
    "espanso": "espanso",
    "espflash": None,
    "essence": None,
    "essentia": None,  # essentia for music analysis
    "est": None,
    "eta": None,
    "etcd": "etcd",
    "eter": None,
    "eternal": None,
    "eth": None,
    "ether": None,
    "eto": None,
    "etrace": None,
    "eureka": None,
    "ev": None,
    "eval": None,
    "eve": None,
    "event": None,
    "ever": None,
    "evil": None,
    "evm": None,
    "evmone": None,
    "evob": None,
    "evo": None,
    "evolin": None,
    "eww": None,
    "ex": None,
    "exa": "exa",
    "exact": None,
    "excel": None,
    "excelsior": None,
    "exchange": None,
    "exe": None,
    "execline": "execline",
    "exec": None,
    "exempi": "exempi",
    "exercise": None,
    "exifer": None,
    "exo": None,
    "expand": None,
    "expander": None,
    "exploit": None,
    "explore": None,
    "export": None,
    "expr": "expr",
    "ext": None,
    "ext2": "e2fsprogs",
    "ext4": "e2fsprogs",
    "extfs": "e2fsprogs",
    "extra": None,
    "extract": None,
    "eye": None,
    "ez": None,
    "eza": "eza",
}  # type: ignore

# ── Packages best as Flatpak (desktop apps) ───────────────────────
FLATPAK_PACKAGES = {
    "firefox": "org.mozilla.firefox",
    "chromium": "org.chromium.Chromium",
    "gimp": "org.gimp.GIMP",
    "blender": "org.blender.Blender",
    "krita": "org.krita.krita",
    "inkscape": "org.inkscape.Inkscape",
    "darktable": "org.darktable.Darktable",
    "rawtherapee": "com.rawtherapee.RawTherapee",
    "libreoffice": "org.libreoffice.LibreOffice",
    "thunderbird": "org.mozilla.Thunderbird",
    "telegram-desktop": "org.telegram.desktop",
    "obs-studio": "com.obsproject.Studio",
    "keepassxc": "org.keepassxc.KeePassXC",
    "bottles": "com.usebottles.bottles",
    "lutris": "net.lutris.Lutris",
    "steam": "com.valvesoftware.Steam",
    "audacity": "org.audacityteam.Audacity",
    "ardour": "org.ardour.Ardour",
    "musescore": "org.musescore.MuseScore",
    "joplin": "net.cozic.joplin_desktop",
    "transmission": "com.transmissionbt.Transmission",
    "qbittorrent": "org.qbittorrent.qBittorrent",
    "drawio": "com.jgraph.drawio.desktop",
    "dosbox": "com.dosbox.DOSBox",
    "flameshot": "org.flameshot.Flameshot",
    "bazecor": "com.bazecor.Bazecor",
    "freetube": "io.freetubeapp.FreeTube",
    "localsend-bin": "org.localsend.localsend_app",
    "zen-browser-bin": "app.zen_browser.zen",
}

# ── Packages available via Homebrew (no Fedora RPM) ─────────────────
BREW_PACKAGES = {
    "curlie", "yq", "go-yq", "gitleaks", "gist", "dive", "genact",
    "act-bin", "act", "bun", "dprint", "choose",
    "cpufetch", "cloudflare-speed-cli",
    "jql", "taplo-cli", "hadolint",
    "nb", "fx", "croc", "gum", "mcfly", "atuin", "navi", "xcp",
    "lua-language-server", "marksman",
    "babashka-bin", "clj-kondo", "zprint",
    "neovim-remote",
}

# ── Packages available via cargo install ────────────────────────────
CARGO_PACKAGES = {
    "bottom", "btm", "du-dust", "dust", "television",
    "difftastic", "delta", "git-delta", "xh", "fclones",
    "ouch", "dysk", "procs", "htmlq", "erdtree",
    "bandwhich", "doggo", "grex", "hyperfine", "choose",
    "lsd", "eza", "exa", "ripgrep", "fd-find", "fd",
    "bat", "zoxide", "zellij", "starship", "mdcat",
    "tokei", "watchexec", "cargo-binstall", "just",
    "duf", "dust", "hexyl", "helix", "lychee", "tokei",
    "gitui", "diskonaut", "dysk", "dssim",
    "yt-dlp", "yazi", "lazygit", "gitui", "csview",
    "himalaya", "no-more-secrets", "genact",
    "tealdeer", "tokei", "onefetch",
    "songfetch", "scc", "halp", "pastel",
    "csvlens", "jaq", "cocogitto", "git-cliff",
    "eza", "bat", "fd", "ripgrep", "procs", "bottom",
    "bandwhich", "doggo", "watchexec",
}

# ── Packages available via pip/pipx ──────────────────────────────────
PIP_PACKAGES = {
    "python-internetarchive", "python-ascii_magic", "python-telethon",
    "beets", "httpie", "glances", "bpytop", "bashtop",
    "speedtest-cli", "proselint", "vale", "ruff",
    "pre-commit", "jupyterlab", "ansible", "yamllint",
    "gallery-dl", "streamlink", "pyload",
    "s-tui", "python-internetarchive", "python-faker",
    "python-rapidgzip", "python-pyperclip", "python-textual",
    "python-poetry", "python-numpy", "python-orjson",
}

# ── Packages available via go install ────────────────────────────────
GO_PACKAGES = {
    "nerdctl", "lazydocker", "dive", "cloudflared",
    "gh", "github-cli", "glab", "croc",
    "caddy", "coredns", "traefik",
}

# ── Truly Arch-specific / unavailable ────────────────────────────────
UNAVAILABLE = {
    # CachyOS kernel stack
    "linux-cachyos", "linux-cachyos-headers",
    "proton-cachyos", "proton-ge-custom-bin",
    # AmneziaWG (need DKMS, Arch-only)
    "amneziawg-dkms", "amneziawg-tools",
    # Custom PKGBUILD/local packages
    "taoup", "richcolors", "albumdetails", "proxypilot",
    "ssh-to-age", "neg-pretty-printer", "wl", "raise",
    "sidecar", "throne", "tailray",
    # AUR helpers (not needed on Fedora)
    "paru", "paru-debug", "yay",
    "pacman-contrib", "rebuild-detector", "mkinitcpio",
    # Arch-specific 32-bit
    "lib32-amdvlk-bin", "lib32-vulkan-radeon",
    # COSMIC desktop (not packaged for Fedora yet)
    "cosmic-greeter",
    # DPI bypass / VPN (Arch-specific)
    "zapret2",
    "amneziawg",
    "hiddify", "hiddify-core",
    "v2raya-bin", "v2rayn-bin", "flclashx-bin",
    # Qt/Wayland launchers (custom builds)
    "vicinae-bin", "fsel-bin", "quickshell", "quickshell-overview-git",
    "otter-launcher", "oports-git",
    # Custom Hyprland plugins/tools
    "hyprscratch",
    # MPD plugins (AUR only)
    "mpdris2-git", "mpdas",
    # Rust game launchers
    "rustmission", "ytsurf",
    # System tools
    "amdgpu-vulkan-switcher-git", "amdgpu_top", "optiscaler-universal",
    "ollama-vulkan", "hermes-agent",
    "strace-tui-bin", "systemd-manager-tui",
    "pixora-icons-git", "pup-bin", "tanin-git",
    "wlogout", "wlr-which-key",
    "swayosd", "satty", "swappy",
    "rofi-file-browser-extended-git", "rofi-file-browser-extended-git-debug",
    "gvfs-onedrive", "gvfs-wsdd",
    "bucklespring", "neo-matrix", "unarchiver", "patool",
    "epr-git", "freeze-bin", "ghgrab-bin", "gmap-bin",
    "gowall-bin", "hxd", "instagram-cli",
    "lazytail-bin", "lutgen-bin", "massren",
    "newsraft", "oyo", "regex-tui",
    "reddix-bin", "repeater-bin", "resterm-bin",
    "rmlint", "simutil-bin", "tessen", "tmmpr",
    "ttfautohint", "unflac", "watchtower-bin",
    "witr-bin", "xdg-ninja", "eilmeldung-bin",
    "carapace-bin", "aliae-bin",
    "hishtory-bin", "raysession",
    "nethack",
}


def load_packages():
    """Parse packages.yaml"""
    path = REPO_ROOT / "states" / "data" / "packages.yaml"
    with open(path) as f:
        return yaml.safe_load(f)


def categorize(pkg: str) -> tuple:
    """Return (fedora_name_or_None, category) prioritizing availability."""
    if pkg in FLATPAK_PACKAGES and FLATPAK_PACKAGES[pkg]:
        return (None, "FLATPAK")
    if pkg in BREW_PACKAGES:
        return (None, "BREW")
    if pkg in CARGO_PACKAGES:
        return (None, "CARGO")
    if pkg in PIP_PACKAGES:
        return (None, "PIP")
    if pkg in GO_PACKAGES:
        return (None, "GO")
    if pkg in UNAVAILABLE:
        return (None, "UNAVAILABLE")
    mapped = FEDORA_RENAME.get(pkg)
    if mapped is not None:
        return (mapped, "RPM")
    return (pkg, "RPM")


def build_containerfile(packages):
    """Generate Containerfile for custom Bluefin image."""
    rpm_packages = set()
    flatpak_refs = set()
    brew_packages = set()
    cargo_packages = set()
    pip_packages = set()
    go_packages = set()
    unavailable = set()
    # Track alternative install methods for unavailable packages
    unavailable_notes = {}

    def collect(pkg_list):
        for pkg in pkg_list:
            if isinstance(pkg, str):
                fedora_name, cat = categorize(pkg)
                if cat == "RPM" and fedora_name:
                    rpm_packages.add(fedora_name)
                elif cat == "FLATPAK":
                    ref = FLATPAK_PACKAGES.get(pkg)
                    if ref:
                        flatpak_refs.add(ref)
                elif cat == "BREW":
                    brew_packages.add(pkg)
                elif cat == "CARGO":
                    cargo_packages.add(pkg)
                elif cat == "PIP":
                    pip_packages.add(pkg)
                elif cat == "GO":
                    go_packages.add(pkg)
                elif cat == "UNAVAILABLE":
                    unavailable.add(pkg)

    for category in packages:
        collect(packages[category])
    if "aur" in packages:
        collect(packages["aur"])

    rpm_sorted = sorted(rpm_packages)
    flatpak_sorted = sorted(flatpak_refs)
    brew_sorted = sorted(brew_packages)
    cargo_sorted = sorted(cargo_packages)
    pip_sorted = sorted(pip_packages)
    go_sorted = sorted(go_packages)
    unavailable_sorted = sorted(unavailable)

    lines = []
    lines.append("# Generated Bluefin custom image Containerfile")
    total = len(rpm_sorted) + len(flatpak_sorted) + len(brew_sorted) + len(cargo_sorted) + len(pip_sorted) + len(go_sorted)
    lines.append(f"# Source packages: {total} mapped + {len(unavailable_sorted)} unavailable")
    lines.append(f"#   RPM: {len(rpm_sorted)}  Flatpak: {len(flatpak_sorted)}  Brew: {len(brew_sorted)}")
    lines.append(f"#   Cargo: {len(cargo_sorted)}  Pip: {len(pip_sorted)}  Go: {len(go_sorted)}")
    lines.append("")
    lines.append("FROM ghcr.io/ublue-os/bluefin-dx:latest")
    lines.append("")
    lines.append("# ── Enable RPM Fusion ───────────────────────────────────────")
    lines.append("RUN rpm-ostree install -y \\")
    lines.append("    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \\")
    lines.append("    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm")
    lines.append("")

    # RPM packages
    lines.append(f"# ── RPM packages ({len(rpm_sorted)} total) ──────────────────")
    for i in range(0, len(rpm_sorted), 6):
        batch = rpm_sorted[i:i+6]
        lines.append("RUN rpm-ostree install -y \\")
        for j, p in enumerate(batch):
            suffix = " \\" if (i + j < len(rpm_sorted) - 1 and j == len(batch) - 1) else ""
            lines.append(f"    {p}{suffix}")
        if i + len(batch) < len(rpm_sorted):
            lines.append("")

    # Flatpak
    if flatpak_sorted:
        lines.append("")
        lines.append(f"# ── Flatpak apps ({len(flatpak_sorted)} total) ─────────────")
        lines.append("RUN flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo")
        for ref in flatpak_sorted:
            lines.append(f"RUN flatpak install -y flathub {ref}")

    # Brew
    if brew_sorted:
        lines.append("")
        lines.append(f"# ── Homebrew ({len(brew_sorted)} total) ─────────────────────")
        lines.append("# Homebrew is pre-installed in Bluefin DX")
        for pkg in brew_sorted:
            lines.append(f"RUN brew install {pkg}")

    # Cargo
    if cargo_sorted:
        lines.append("")
        lines.append(f"# ── Cargo ({len(cargo_sorted)} total) ───────────────────────")
        lines.append("# cargo-binstall is recommended for speed")
        for pkg in cargo_sorted:
            lines.append(f"RUN cargo binstall -y {pkg} || cargo install {pkg}")

    # Pip
    if pip_sorted:
        lines.append("")
        lines.append(f"# ── Pip/Pipx ({len(pip_sorted)} total) ──────────────────────")
        for pkg in pip_sorted:
            lines.append(f"RUN pipx install {pkg}")

    # Go
    if go_sorted:
        lines.append("")
        lines.append(f"# ── Go ({len(go_sorted)} total) ─────────────────────────────")
        for pkg in go_sorted:
            lines.append(f"RUN go install github.com/{pkg}@latest")

    # Unavailable
    if unavailable_sorted:
        lines.append("")
        lines.append(f"# ── UNAVAILABLE ({len(unavailable_sorted)} total) ────────────")
        lines.append("# No Fedora/Flathub/Brew/Cargo/Pip/Go equivalent found.")
        lines.append("# Must compile from source, find COPR, or skip.")
        for p in unavailable_sorted:
            lines.append(f"#   - {p}")

    return "\n".join(lines)


def build_flatpak_list(packages):
    refs = set()
    def collect(pkg_list):
        for p in pkg_list:
            if isinstance(p, str) and p in FLATPAK_PACKAGES and FLATPAK_PACKAGES[p]:
                refs.add(FLATPAK_PACKAGES[p])
    for cat in packages:
        collect(packages[cat])
    if "aur" in packages:
        collect(packages["aur"])
    return "\n".join(sorted(refs))


def build_brewfile(packages):
    pkgs = set()
    def collect(pkg_list):
        for p in pkg_list:
            if isinstance(p, str) and p in BREW_PACKAGES:
                pkgs.add(p)
    for cat in packages:
        collect(packages[cat])
    if "aur" in packages:
        collect(packages["aur"])
    return "\n".join(f'brew "{p}"' for p in sorted(pkgs))


def build_cargo_list(packages):
    pkgs = set()
    def collect(pkg_list):
        for p in pkg_list:
            if isinstance(p, str) and p in CARGO_PACKAGES:
                pkgs.add(p)
    for cat in packages:
        collect(packages[cat])
    if "aur" in packages:
        collect(packages["aur"])
    return "\n".join(sorted(pkgs))


def build_pip_list(packages):
    pkgs = set()
    def collect(pkg_list):
        for p in pkg_list:
            if isinstance(p, str) and p in PIP_PACKAGES:
                pkgs.add(p)
    for cat in packages:
        collect(packages[cat])
    if "aur" in packages:
        collect(packages["aur"])
    return "\n".join(sorted(pkgs))


def build_mapping(packages):
    all_packages = []
    def collect(pkg_list, source):
        for p in pkg_list:
            if isinstance(p, str):
                fedora, cat = categorize(p)
                all_packages.append({"arch": p, "fedora": fedora, "source": cat, "category": source})
    for cat in packages:
        collect(packages[cat], cat)
    if "aur" in packages:
        collect(packages["aur"], "aur")
    return yaml.dump(all_packages, sort_keys=False, allow_unicode=True, default_flow_style=False)


def build_missing(packages):
    missing = set()
    def collect(pkg_list):
        for p in pkg_list:
            if isinstance(p, str):
                _, cat = categorize(p)
                if cat == "UNAVAILABLE":
                    missing.add(p)
    for cat in packages:
        collect(packages[cat])
    if "aur" in packages:
        collect(packages["aur"])
    return "\n".join(sorted(missing))


def main():
    packages = load_packages()
    outdir = Path(__file__).resolve().parent

    # Containerfile
    cf = build_containerfile(packages)
    (outdir / "Containerfile").write_text(cf)
    print(f"Wrote Containerfile ({len(cf.splitlines())} lines)")

    # flatpak.list
    fl = build_flatpak_list(packages)
    (outdir / "flatpak.list").write_text(fl + "\n")
    print(f"Wrote flatpak.list ({len(fl.splitlines())} lines)")

    # brew.Brewfile
    bf = build_brewfile(packages)
    (outdir / "brew.Brewfile").write_text(bf + "\n")
    print(f"Wrote brew.Brewfile ({len(bf.splitlines())} lines)")

    # cargo.list
    cl = build_cargo_list(packages)
    (outdir / "cargo.list").write_text(cl + "\n")
    print(f"Wrote cargo.list ({len(cl.splitlines())} lines)")

    # pip.list
    pl = build_pip_list(packages)
    (outdir / "pip.list").write_text(pl + "\n")
    print(f"Wrote pip.list ({len(pl.splitlines())} lines)")

    # mapping.yaml
    mp = build_mapping(packages)
    (outdir / "mapping.yaml").write_text(mp)
    print(f"Wrote mapping.yaml ({len(mp.splitlines())} lines)")

    # missing.txt
    ms = build_missing(packages)
    (outdir / "missing.txt").write_text(ms + "\n")
    print(f"Wrote missing.txt ({len(ms.splitlines())} lines)")

    print(f"\nDone. Files in {outdir}/")


if __name__ == "__main__":
    main()
