context.objects = [
    { factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "fmod_sink"
            node.description = "FMOD_Game_Sink"
            media.class      = "Audio/Sink"
            audio.position   = [ FL FR ]
            audio.format     = "F32LE"
            audio.channels   = 2
            audio.rate       = 48000
            monitor.passthrough = true
            adapter.auto-port-config = {
                mode    = dsp
                monitor = true
            }
        }
    }
]
