{ config, pkgs, lib, ... }:

let
  inherit (lib) mkEnableOption mkIf types;
  cfg = config.boot.loader.limine;

  nixosFsUuid = "10d42115-ab09-4142-bb50-9ec56fcda509";
  nixosPartuuid = "4d2585cf-07cf-4ad8-aa52-3c62d780cd03";

  # Script to generate Limine entries from the current NixOS generation.
  # Reads boot.json from the system profile, extracts kernel/initrd paths,
  # and writes entries to /boot/limine.cfg on the ESP.
  generate-entries = pkgs.writeShellApplication {
    name = "limine-generate-entries";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      set -euo pipefail
      ESP_MOUNT="''${1:-/boot}"
      CONFIG="$ESP_MOUNT/limine.cfg"
      MARKER="# @nixos-generations"
      PROFILE="$(readlink -f /run/current-system)"

    [ -f "$PROFILE/boot.json" ] || { echo "limine: no boot.json in $PROFILE" >&2; exit 0; }
    [ -w "$CONFIG" ] || [ -w "$(dirname "$CONFIG")" ] || { echo "limine: config not writable: $CONFIG" >&2; exit 1; }

    label=$(jq -r '.["org.nixos.bootspec.v1"].label // "NixOS"' "$PROFILE/boot.json")
    kernel=$(jq -r '.["org.nixos.bootspec.v1"].kernel' "$PROFILE/boot.json")
    initrd=$(jq -r '.["org.nixos.bootspec.v1"].initrd' "$PROFILE/boot.json")
    init=$(jq -r '.["org.nixos.bootspec.v1"].init' "$PROFILE/boot.json")
    params=$(jq -r '.["org.nixos.bootspec.v1"].kernelParams | join(" ")' "$PROFILE/boot.json")

    [ -n "$kernel" ] && [ -n "$initrd" ] || { echo "limine: no kernel/initrd in boot.json" >&2; exit 1; }

    # Strip existing NixOS entries (from marker to end)
    sed -i "/^$MARKER/,\$d" "$CONFIG" 2>/dev/null || true

    {
      echo ""
      echo "# --- NixOS generations (auto-generated by NixOS boot.loader.limine) ---"
      echo "$MARKER"
      echo ""
      echo ":NixOS (${label})"
      echo "    PROTOCOL=linux"
      echo "    COMMENT=NixOS ${label}"
      echo "    KERNEL_CMDLINE=root=PARTUUID=${nixosPartuuid} rw init=${init} ${params}"
      echo "    KERNEL_PATH=uuid(${nixosFsUuid})://''${kernel#/}"
      echo "    MODULE_PATH=uuid(${nixosFsUuid})://''${initrd#/}"
      echo ""
    } >> "$CONFIG"

    echo "limine: wrote NixOS entry to $CONFIG"
  '';
  };

in
{
  options.boot.loader.limine = {
    enable = mkEnableOption "Limine bootloader integration";
    efiSysMountPoint = lib.mkOption {
      type = types.str;
      default = "/boot";
      description = "ESP mount point where limine.cfg is located.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Disable systemd-boot — Limine binary is deployed by CachyOS Salt state.
    # This module only writes generation entries to /boot/limine.cfg.
    boot.loader.systemd-boot.enable = lib.mkForce false;

    # Systemd service to sync NixOS entries to limine.cfg on activation
    systemd.services.limine-sync = {
      description = "Sync NixOS generation entry to Limine bootloader config";
      wantedBy = [ "multi-user.target" ];
      after = [ "local-fs.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        # Run the generate script with the ESP mount point
        ExecStart = "${generate-entries}/bin/limine-generate-entries ${cfg.efiSysMountPoint}";
      };
    };

    # Also run on nixos-rebuild activation
    system.activationScripts.limine = lib.stringAfter [ "etc" ] ''
      if [ -d ${cfg.efiSysMountPoint} ]; then
        ${generate-entries}/bin/limine-generate-entries ${cfg.efiSysMountPoint} || true
      fi
    '';
  };
}
