context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      node.description = "Harman Sub Shelf EQ"
      media.name = "Harman EQ"
      filter.graph = {
        nodes = [
          {
            type  = lv2
            name  = "eq"
            plugin = "http://lsp-plug.in/plugins/lv2/para_equalizer_x32_stereo"
            control = {
              "enabled" = 1
              "g_in"    = 1.0
              "g_out"   = 1.0
              "ft_0"    = 5
              "fm_0"    = 0
              "f_0"     = 55.0
              "g_0"     = 2.239
              "q_0"     = 0.707
              "s_0"     = 0
            }
          }
        ]
        inputs  = [ "eq:in_l" "eq:in_r" ]
        outputs = [ "eq:out_l" "eq:out_r" ]
      }
      capture.props = {
        node.name      = "harman_shelf_sink"
        media.class    = "Audio/Sink"
        audio.channels = 2
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name      = "harman_shelf_source"
        media.class    = "Audio/Source"
        audio.channels = 2
        audio.position = [ FL FR ]
      }
    }
  }
]
