monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-Sony_Interactive_Entertainment_DualSense.*"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  },
  {
    matches = [
      {
        alsa.card_name = "HDSPe24048964"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
        api.alsa.period-size = 256
        api.alsa.headroom = 256
        api.alsa.disable-batch = true
        priority.session = 0
        priority.driver = 0
        node.nick = "RME AIO Pro"
      }
    }
  },
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
