(define-module (custom packages slsa-verifier)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system gnu)
  #:use-module (guix licenses))

(define-public slsa-verifier
  (package
    (name "slsa-verifier")
    (version "2.7.1")
    (source (origin
              (method url-fetch)
              (uri "https://github.com/slsa-framework/slsa-verifier/releases/download/v2.7.1/slsa-verifier-linux-amd64")
              (sha256 (base32 "0f836panph6bc4pvvip20fgqc9sa68s1g3ppivl9ah89573vwvcl"))))
    (build-system gnu-build-system)
    (arguments
     '(#:tests? #f #:strip-binaries? #f #:validate-runpath? #f
       #:phases (modify-phases %standard-phases
                  (delete 'bootstrap) (delete 'configure) (delete 'check)
                  (delete 'build) (delete 'patch-usr-bin-file)
                  (delete 'patch-source-shebangs)
                  (delete 'patch-generated-file-shebangs)
                  (replace 'install
                    (lambda* (#:key outputs #:allow-other-keys)
                      (let* ((out (assoc-ref outputs "out"))
                             (bin (string-append out "/bin"))
                             (script (car (find-files "." "^slsa-verifier-linux-amd64$"))))
                        (mkdir-p bin)
                        (copy-file script (string-append bin "/slsa-verifier"))
                        (chmod (string-append bin "/slsa-verifier") #o555))
                      #t)))))
    (supported-systems '("x86_64-linux"))
    (home-page "https://github.com/slsa-framework/slsa-verifier")
    (synopsis "Verify SLSA provenance attestations")
    (description "Verifies SLSA provenance attestations generated by CI/CD builders.")
    (license expat)))

slsa-verifier