#!/usr/bin/env zsh
# Deploy CachyOS rootfs to ext4 partition with existing ESP.
#
# Usage:
#   sudo ./scripts/deploy-cachyos-ext4.sh /dev/nvme1n1p4 /dev/nvme1n1p1 [ROOTFS_DIR]
#
# Default rootfs: /mnt/one/cachyos-root
#
# Layout:
#   /dev/nvme1n1p1  ESP (already exists, FAT32)
#   /dev/nvme1n1p4  ext4 root partition
#
# Requires: rsync, mkinitcpio, limine, efibootmgr

set -euo pipefail

ROOT_PART="${1:-}"
ESP_PART="${2:-}"
ROOTFS="${3:-/mnt/one/cachyos-root}"
MNT="/mnt/deploy-ext4"

# -------------------------------------------------------------------
# Validation
# -------------------------------------------------------------------

if [[ -z "$ROOT_PART" ]] || [[ -z "$ESP_PART" ]]; then
	echo "usage: $0 <root_partition> <esp_partition> [ROOTFS_DIR]" >&2
	echo "  e.g. $0 /dev/nvme1n1p4 /dev/nvme1n1p1 /mnt/one/cachyos-root" >&2
	exit 1
fi

if [[ $EUID -ne 0 ]]; then
	echo "error: must run as root" >&2
	exit 1
fi

if [[ ! -b "$ROOT_PART" ]]; then
	echo "error: $ROOT_PART is not a block device" >&2
	exit 1
fi

if [[ ! -b "$ESP_PART" ]]; then
	echo "error: $ESP_PART is not a block device" >&2
	exit 1
fi

if [[ ! -d "$ROOTFS/usr/bin" ]]; then
	echo "error: $ROOTFS doesn't look like a rootfs (no usr/bin)" >&2
	echo "  run bootstrap-cachyos.sh first" >&2
	exit 1
fi

for cmd in rsync blkid chroot efibootmgr; do
	if ! command -v "$cmd" &>/dev/null; then
		echo "error: required command '$cmd' not found" >&2
		exit 1
	fi
done

# -------------------------------------------------------------------
# Confirmation
# -------------------------------------------------------------------

echo "========================================"
echo " CachyOS Deploy (ext4)"
echo "========================================"
echo ""
echo "  Root partition: $ROOT_PART"
echo "  ESP partition:  $ESP_PART"
echo "  Rootfs:         $ROOTFS"
echo "  Mount point:    $MNT"
echo ""
echo "  WARNING: ALL DATA ON $ROOT_PART WILL BE DESTROYED"
echo "           ESP ($ESP_PART) will be preserved but Limine will be installed"
echo ""
read -r "confirm?  Type 'yes' to continue: "
if [[ "$confirm" != "yes" ]]; then
	echo "Aborted."
	exit 0
fi

# -------------------------------------------------------------------
# Cleanup trap
# -------------------------------------------------------------------

cleanup() {
	echo "==> Cleaning up mounts..."
	umount -R "$MNT" 2>/dev/null || true
	rmdir "$MNT" 2>/dev/null || true
}
trap cleanup EXIT

mkdir -p "$MNT"

# -------------------------------------------------------------------
# Part 1: Prepare root partition
# -------------------------------------------------------------------

echo ""
echo "==> Checking filesystem on $ROOT_PART..."
if ! blkid -s TYPE -o value "$ROOT_PART" | grep -q '^ext4$'; then
	echo "error: $ROOT_PART is not ext4" >&2
	exit 1
fi

echo "==> Mounting root partition..."
mount "$ROOT_PART" "$MNT"

echo "==> Clearing root partition (keeping lost+found)..."
find "$MNT" -mindepth 1 -maxdepth 1 ! -name 'lost+found' -exec rm -rf {} +

echo "==> Copying rootfs (this takes a while)..."
rsync -aAH --info=progress2 "$ROOTFS/" "$MNT/"

# -------------------------------------------------------------------
# Part 2: Copy kernel/initramfs to ESP before mounting
# -------------------------------------------------------------------

echo "==> Preparing ESP mount..."
ESPMNT="/tmp/esp-mount"
mkdir -p "$ESPMNT"
mount "$ESP_PART" "$ESPMNT"

echo "==> Ensuring boot directory structure on ESP..."
mkdir -p "$ESPMNT/EFI/BOOT"

# Copy Limine EFI binary if exists in rootfs
if [[ -f "$MNT/usr/share/limine/BOOTX64.EFI" ]]; then
	echo "==> Copying Limine EFI binary..."
	cp "$MNT/usr/share/limine/BOOTX64.EFI" "$ESPMNT/EFI/BOOT/BOOTX64.EFI"
fi

# Copy kernel and initramfs from rootfs boot to ESP
echo "==> Copying kernel and initramfs to ESP..."
if [[ -f "$MNT/boot/vmlinuz-linux-cachyos-lts" ]]; then
	cp "$MNT/boot/vmlinuz-linux-cachyos-lts" "$ESPMNT/"
fi
if [[ -f "$MNT/boot/initramfs-linux-cachyos-lts.img" ]]; then
	cp "$MNT/boot/initramfs-linux-cachyos-lts.img" "$ESPMNT/"
fi
if [[ -f "$MNT/boot/initramfs-linux-cachyos-lts-fallback.img" ]]; then
	cp "$MNT/boot/initramfs-linux-cachyos-lts-fallback.img" "$ESPMNT/"
fi

# Unmount temporary ESP mount
umount "$ESPMNT"
rmdir "$ESPMNT"

# Now mount ESP to /boot inside root
echo "==> Mounting ESP to /boot..."
mkdir -p "$MNT/boot"
mount "$ESP_PART" "$MNT/boot"

# -------------------------------------------------------------------
# Part 3: Chroot configuration
# -------------------------------------------------------------------

echo "==> Generating fstab..."
ROOT_UUID=$(blkid -s UUID -o value "$ROOT_PART")
ESP_UUID=$(blkid -s UUID -o value "$ESP_PART")

cat >"$MNT/etc/fstab" <<FSTAB
# CachyOS — ext4 root + ESP (generated by deploy-cachyos-ext4.sh)
UUID=${ROOT_UUID}  /              ext4  defaults,noatime          0  0
UUID=${ESP_UUID}   /boot          vfat  umask=0077                0  1
FSTAB

echo "==> Entering chroot for final configuration..."

# Bind-mount pseudo-filesystems
mount --bind /dev "$MNT/dev"
mount --bind /dev/pts "$MNT/dev/pts"
mount -t proc proc "$MNT/proc"
mount -t sysfs sys "$MNT/sys"
mount -t efivarfs efivarfs "$MNT/sys/firmware/efi/efivars" 2>/dev/null || true

chroot "$MNT" /bin/bash <<CHROOT
set -euo pipefail

# --- mkinitcpio: no lvm2 hook needed for ext4 ---
echo "  Rebuilding initramfs..."
mkinitcpio -P

# --- Limine bootloader config ---
echo "  Writing Limine config..."
cat > /boot/limine.conf <<'LIMINE'
timeout: 5
default_entry: 1
interface_branding: CachyOS

/CachyOS LTS
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos-lts
    kernel_cmdline: root=UUID=${ROOT_UUID} rw quiet splash
    module_path: boot():/initramfs-linux-cachyos-lts.img

/CachyOS LTS (fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos-lts
    kernel_cmdline: root=UUID=${ROOT_UUID} rw
    module_path: boot():/initramfs-linux-cachyos-lts-fallback.img

/CachyOS
    //CachyOS LTS
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos-lts
    kernel_cmdline: root=UUID=${ROOT_UUID} rw quiet splash
    module_path: boot():/initramfs-linux-cachyos-lts.img

    //CachyOS LTS (fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos-lts
    kernel_cmdline: root=UUID=${ROOT_UUID} rw
    module_path: boot():/initramfs-linux-cachyos-lts-fallback.img
LIMINE

# --- Register in UEFI boot menu ---
echo "  Registering UEFI boot entry..."
efibootmgr --create --disk "${ESP_PART%p*}" --part "${ESP_PART##*p}" \
    --label "CachyOS" --loader 'EFI\BOOT\BOOTX64.EFI' 2>/dev/null || \
    echo "  WARNING: efibootmgr failed (expected if not booted in UEFI mode)"
CHROOT

# -------------------------------------------------------------------
# Part 4: Verification
# -------------------------------------------------------------------

echo ""
echo "==> Verification:"

checks=(
	"boot/vmlinuz-linux-cachyos-lts:kernel on ESP"
	"boot/initramfs-linux-cachyos-lts.img:initramfs on ESP"
	"boot/limine.conf:Limine config"
	"boot/EFI/BOOT/BOOTX64.EFI:Limine EFI binary"
	"etc/fstab:fstab"
)

ok=true
for check in "${checks[@]}"; do
	path="${check%%:*}"
	label="${check#*:}"
	if [[ -e "$MNT/$path" ]]; then
		echo "  OK    $label"
	else
		echo "  FAIL  $label ($MNT/$path missing)"
		ok=false
	fi
done

# -------------------------------------------------------------------
# Write post-boot instructions to target filesystem
# -------------------------------------------------------------------

cat >"$MNT/root/POST-BOOT.md" <<'POSTBOOT'
# CachyOS Post-Boot Guide (ext4)

## 1. Set passwords (in chroot before reboot, or after first boot)

    passwd          # root
    passwd neg      # user

## 2. Network

NetworkManager starts automatically. For Wi-Fi:

    nmcli device wifi list
    nmcli device wifi connect <SSID> --ask

Verify:

    ping -c1 archlinux.org

## 3. Mount XFS data disks

    sudo vgchange -ay xenon argon
    sudo mkdir -p /mnt/{one,zero}
    sudo mount /dev/mapper/xenon-one /mnt/one
    sudo mount /dev/mapper/argon-zero /mnt/zero

Salt repo and rootfs backup are on xenon-one:

    /mnt/one/salt/              ← full salt repo
    /mnt/one/cachyos-root/      ← original rootfs

## 4. Copy salt repo to home

    mkdir -p ~/src
    cp -a /mnt/one/salt ~/src/cfg
    cd ~/src/cfg

## 5. Apply Salt + chezmoi

    cd ~/src/cfg
    scripts/salt-apply.sh

This runs:
  - Salt verification state (cachyos.sls) — checks packages, services, configs
  - chezmoi apply — deploys all dotfiles (renders .tmpl files via gopass)

## 6. Switch git remote to SSH (if cloned via HTTPS)

    cd ~/src/cfg
    git remote set-url origin git@github.com:neg-serg/salt.git

## 7. Add XFS mounts to fstab (permanent)

    echo '/dev/mapper/xenon-one  /mnt/one  xfs  noatime  0  0' | sudo tee -a /etc/fstab
    echo '/dev/mapper/argon-zero /mnt/zero xfs  noatime  0  0' | sudo tee -a /etc/fstab

## 8. Reboot and verify

    sudo reboot

After reboot, everything should be functional:
  - Hyprland (compositor), kitty (terminal), rofi (launcher)
  - gopass backend unlock path, gopass (secrets)
  - Mail (mbsync), calendar (vdirsyncer)
  - MPD (music), mpv (video)
  - All user services auto-start via systemd
POSTBOOT

echo "  OK    post-boot guide written to /root/POST-BOOT.md"

# -------------------------------------------------------------------
# Console output
# -------------------------------------------------------------------

echo ""
if $ok; then
	echo "==> Deploy complete."
else
	echo "==> Deploy finished with warnings — check output above."
fi

echo ""
echo "Before reboot (still in chroot/live USB):"
echo "  1. Set passwords:    chroot \"$MNT\" passwd && chroot \"$MNT\" passwd neg"
echo "  2. Unmount:          umount -R \"$MNT\""
echo "  3. Reboot:           select 'CachyOS' in UEFI boot menu"
echo ""
echo "After first boot as neg:"
echo "  4. Mount XFS:        sudo vgchange -ay xenon argon"
echo "                       sudo mkdir -p /mnt/{one,zero}"
echo "                       sudo mount /dev/mapper/xenon-one /mnt/one"
echo "                       sudo mount /dev/mapper/argon-zero /mnt/zero"
echo "  5. Copy salt repo:   cp -a /mnt/one/salt ~/src/cfg"
echo "  6. Apply config:     cd ~/src/cfg && scripts/salt-apply.sh"
echo "  7. Add to fstab:     see /root/POST-BOOT.md (step 7)"
echo ""
echo "Full guide saved to: $MNT/root/POST-BOOT.md"
echo "Salt repo on XFS:    /mnt/one/salt/"

# Disable automatic cleanup — user handles unmount manually after setting passwords
trap - EXIT