#!/usr/bin/env python3
"""Generate Salt state, macro, and data indexes for Claude Code memory.

Parses macro .jinja files for signatures, renders .sls with mock Jinja env
for state IDs and require chains, and summarizes YAML data files.

Reuses parsing infrastructure from lint-jinja.py.

Outputs markdown to memory/generated/salt-macros.md, salt-states.md, salt-data.md.
"""

import fnmatch
import glob
import importlib.util
import os
import re
import sys
from datetime import datetime

import yaml

# Host model from shared module; lint-jinja.py for Jinja rendering infrastructure
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)


def _load_source_model_helpers():
    from salt_source_model import discover_state_files, enrich_source_metadata

    return discover_state_files, enrich_source_metadata


discover_state_files, enrich_source_metadata = _load_source_model_helpers()

# lint-jinja.py has a hyphenated name — must use importlib.util
_lint_path = os.path.join(SCRIPTS_DIR, "lint-jinja.py")
_spec = importlib.util.spec_from_file_location("lint_jinja", _lint_path)
if not _spec or not _spec.loader:  # pragma: no cover - defensive
    raise ImportError("Cannot load lint-jinja.py")
_lint_jinja = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_lint_jinja)  # type: ignore[attr-defined]

SaltTagExtension = _lint_jinja.SaltTagExtension
_make_render_env = _lint_jinja._make_render_env
_resolve_import_yaml = _lint_jinja._resolve_import_yaml

STATES_DIR = "states"
MEMORY_DIR = os.path.join(
    os.path.expanduser("~"), ".claude", "projects", "-home-neg-src-salt", "memory", "generated"
)
DOCS_DIR = "docs"

_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
HEADER = (
    "<!-- AUTO-GENERATED by scripts/index-salt.py"
    " — do not hand-edit -->\n"
    f"<!-- Last updated: {_ts} -->\n"
)

SALT_DIRECTIVES = frozenset({"include", "extend"})
REQUISITE_KEYS = frozenset(
    {
        "require",
        "watch",
        "onchanges",
        "onfail",
        "prereq",
        "require_in",
        "watch_in",
        "onchanges_in",
        "onfail_in",
    }
)

IMPORT_YAML_RE = re.compile(r"\{%-?\s*import_yaml\s+['\"]([^'\"]+)['\"]\s+as\s+\w+")

# --- Macro parsing ---

MACRO_DEF_RE = re.compile(r"\{%-?\s*macro\s+(\w+)\s*\((.*?)\)\s*-?%\}", re.DOTALL)


def _state_name_from_relpath(relpath):
    rel = relpath.replace("\\", "/")
    if rel.startswith("states/"):
        rel = rel[len("states/") :]
    return rel.removesuffix(".sls").replace("/", ".")


def parse_macros(jinja_files):
    """Parse macro definitions from .jinja files.

    Returns list of (name, params_str, source_file, doc_comment).
    """
    macros = []
    for path in sorted(jinja_files):
        with open(path) as f:
            source = f.read()

        rel = os.path.relpath(path)
        # Find doc comments immediately before macros
        for m in MACRO_DEF_RE.finditer(source):
            name = m.group(1)
            params = m.group(2).strip()
            # Look for {# ... #} comment in the 500 chars before macro
            pre = source[max(0, m.start() - 500) : m.start()]
            doc = ""
            doc_m = re.search(r"\{#\s*(.*?)\s*#\}", pre, re.DOTALL)
            if doc_m:
                doc = doc_m.group(1).strip().split("\n")[0].strip()
            macros.append((name, params, rel, doc))
    return macros


def generate_macros_md(macros):
    """Generate salt-macros.md content."""
    lines = [HEADER, "# Salt Macro Index\n"]

    by_file = {}
    for name, params, src, doc in macros:
        by_file.setdefault(src, []).append((name, params, doc))

    for src in sorted(by_file):
        lines.append(f"\n## `{src}`\n")
        for name, params, doc in by_file[src]:
            lines.append(f"### {name}")
            lines.append(f"```\n{name}({params})\n```")
            if doc:
                lines.append(f"_{doc}_")
            lines.append("")

    return "\n".join(lines) + "\n"


# --- State rendering and dependency extraction ---


def render_states(sls_files):
    """Render .sls files with mock context, extract state IDs and requisites.

    Returns list of (rel_path, state_ids, includes, requires, feature_guards).
    """
    env = _make_render_env()
    results = []
    requested = set(sls_files)
    metadata_by_rel = {
        record.relpath: enrich_source_metadata(record)
        for record in discover_state_files(STATES_DIR)
        if record.relpath in requested
    }

    for path in sorted(sls_files):
        rel = os.path.relpath(path)
        name = path.removeprefix(f"{STATES_DIR}/")
        source_record = metadata_by_rel.get(rel)
        try:
            t = env.get_template(name)
            with open(path) as fh:
                yaml_vars = _resolve_import_yaml(fh.read())
            rendered = t.render(**yaml_vars)
        except Exception:
            feature_guards = source_record.feature_guards if source_record else []
            results.append((rel, [], [], [], feature_guards))
            continue

        state_ids = []
        includes = []
        requires = []

        try:
            for doc in yaml.safe_load_all(rendered):
                if not doc or not isinstance(doc, dict):
                    continue
                for key, val in doc.items():
                    if key == "include":
                        if isinstance(val, list):
                            includes.extend(str(v) for v in val)
                    elif key not in SALT_DIRECTIVES:
                        state_ids.append(key)
                        # Extract require chains
                        if isinstance(val, dict):
                            for state_mod, state_args in val.items():
                                if isinstance(state_args, list):
                                    for arg in state_args:
                                        if isinstance(arg, dict):
                                            for rk in REQUISITE_KEYS:
                                                if rk in arg:
                                                    reqs = arg[rk]
                                                    if isinstance(reqs, list):
                                                        for r in reqs:
                                                            if isinstance(r, dict):
                                                                for mod, sid in r.items():
                                                                    req = f"{mod}: {sid}"
                                                                    requires.append((key, req))
        except Exception:
            pass

        feature_guards = source_record.feature_guards if source_record else []

        results.append((rel, state_ids, includes, requires, feature_guards))

    return results


def generate_states_md(state_results):
    """Generate salt-states.md content."""
    lines = [HEADER, "# Salt State Index\n"]

    for rel, state_ids, includes, requires, guards in state_results:
        state_name = _state_name_from_relpath(rel)
        lines.append(f"\n## {state_name}")
        lines.append(f"**File:** `{rel}`\n")

        if includes:
            lines.append(f"**Includes:** {', '.join(f'`{i}`' for i in includes)}\n")

        if guards:
            lines.append(f"**Feature guards:** {', '.join(f'`{g}`' for g in guards)}\n")

        if state_ids:
            lines.append(f"**State IDs** ({len(state_ids)}):")
            for sid in state_ids:
                lines.append(f"- `{sid}`")
            lines.append("")

        if requires:
            lines.append("**Require chains:**")
            for from_id, to_ref in requires:
                lines.append(f"- `{from_id}` requires `{to_ref}`")
            lines.append("")

    return "\n".join(lines) + "\n"


def build_state_graph(state_results):
    graph = {}
    reverse = {}
    guards_map = {}
    for rel, _, includes, _, guards in state_results:
        name = _state_name_from_relpath(rel)
        clean_includes = [inc.strip() for inc in includes if inc]
        graph[name] = clean_includes
        guards_map[name] = guards
        for inc in clean_includes:
            reverse.setdefault(inc, []).append(name)
        reverse.setdefault(name, reverse.get(name, []))
    return graph, reverse, guards_map


def generate_state_map_docs(graph, reverse, guards_map):
    eng = [
        HEADER,
        "# Salt State Dependency Map\n",
        "Generated from `include:` statements in `states/**/*.sls`.\n",
    ]
    rus = [
        HEADER,
        "# Карта зависимостей Salt\n",
        "Сгенерировано из блоков `include:` в `states/**/*.sls`.\n",
    ]

    def fmt_list(items, empty):
        return ", ".join(f"`{item}`" for item in sorted(set(items))) if items else empty

    for state in sorted(graph):
        includes = graph[state]
        parents = reverse.get(state, [])
        guards = guards_map.get(state, [])

        eng.append(f"\n## `{state}`")
        eng.append(f"**Includes:** {fmt_list(includes, '_None_')}\n")
        eng.append(f"**Included by:** {fmt_list(parents, '_Root_')}\n")
        if guards:
            eng.append(f"**Feature guards:** {fmt_list(guards, '_None_')}\n")

        rus.append(f"\n## `{state}`")
        rus.append(f"**Включает:** {fmt_list(includes, '_Нет_')}\n")
        rus.append(f"**Используется в:** {fmt_list(parents, '_Корень_')}\n")
        if guards:
            rus.append(f"**Фичи:** {fmt_list(guards, '_Нет_')}\n")

    return "\n".join(eng) + "\n", "\n".join(rus) + "\n"


def _yaml_safe(obj):
    """Recursively convert tuples to lists for YAML serialization."""
    if isinstance(obj, dict):
        return {k: _yaml_safe(v) for k, v in obj.items()}
    if isinstance(obj, tuple):
        return [_yaml_safe(i) for i in obj]
    if isinstance(obj, list):
        return [_yaml_safe(i) for i in obj]
    return obj


def write_knowledge_base(macros, state_results, summaries):
    kb = {}

    macros_list = []
    for name, params, src, doc in macros:
        entry = {"name": name, "file": src}
        if params:
            entry["params"] = params
        if doc:
            entry["doc"] = doc
        macros_list.append(entry)
    if macros_list:
        kb["macros"] = macros_list

    states_list = []
    for rel, state_ids, includes, requires, guards in state_results:
        entry = {
            "name": _state_name_from_relpath(rel),
            "file": rel,
        }
        if state_ids:
            entry["state_ids"] = _yaml_safe(state_ids)
        if includes:
            entry["includes"] = _yaml_safe(includes)
        if requires:
            entry["requires"] = _yaml_safe(requires)
        if guards:
            entry["feature_guards"] = _yaml_safe(guards)
        states_list.append(entry)
    if states_list:
        kb["states"] = states_list

    data_list = []
    for rel, info in summaries:
        entry = {"file": rel}
        if info:
            entry["info"] = _yaml_safe(info)
        data_list.append(entry)
    if data_list:
        kb["data"] = data_list

    kb_path = os.path.join(MEMORY_DIR, "salt-knowledge.yaml")
    with open(kb_path, "w") as fh:
        yaml.dump(kb, fh, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"Wrote {kb_path}")


# --- Data file summaries ---


def summarize_data_files():
    """Summarize YAML data files in states/data/."""
    data_dir = os.path.join(STATES_DIR, "data")
    if not os.path.isdir(data_dir):
        return []

    summaries = []
    for path in sorted(glob.glob(os.path.join(data_dir, "*.yaml"))):
        rel = os.path.relpath(path)
        try:
            with open(path) as f:
                data = yaml.safe_load(f.read())
        except Exception:
            summaries.append((rel, "Failed to parse"))
            continue

        if not isinstance(data, dict):
            summaries.append((rel, f"Root type: {type(data).__name__}"))
            continue

        sections = []
        for key, val in data.items():
            if isinstance(val, dict):
                sections.append(f"`{key}` ({len(val)} entries)")
            elif isinstance(val, list):
                sections.append(f"`{key}` ({len(val)} items)")
            else:
                sections.append(f"`{key}`: {val}")

        summaries.append((rel, sections))

    return summaries


def generate_data_md(summaries):
    """Generate salt-data.md content."""
    lines = [HEADER, "# Salt Data File Index\n"]

    for rel, info in summaries:
        basename = os.path.basename(rel)
        lines.append(f"\n## {basename}")
        lines.append(f"**File:** `{rel}`\n")

        if isinstance(info, str):
            lines.append(f"_{info}_\n")
        else:
            for section in info:
                lines.append(f"- {section}")
            lines.append("")

    return "\n".join(lines) + "\n"


def collect_data_usage():
    usage = {}
    CONFIG_REF_RE = re.compile(r"salt://(configs/[^\s'\"]+)")

    for path in glob.glob(os.path.join(STATES_DIR, "**", "*.sls"), recursive=True):
        with open(path) as f:
            content = f.read()

        for match in IMPORT_YAML_RE.finditer(content):
            rel = match.group(1)
            if not rel.startswith("data/"):
                continue
            full = os.path.join(STATES_DIR, rel)
            usage.setdefault(full, set()).add(os.path.relpath(path, STATES_DIR))

        for config_match in CONFIG_REF_RE.finditer(content):
            config_rel = config_match.group(1)
            config_path = os.path.join(STATES_DIR, config_rel)
            if not config_path.endswith(".j2"):
                continue
            if not os.path.isfile(config_path):
                continue
            try:
                with open(config_path) as cf:
                    config_src = cf.read()
            except (OSError, IOError):
                continue
            for j2_match in IMPORT_YAML_RE.finditer(config_src):
                j2_rel = j2_match.group(1)
                if not j2_rel.startswith("data/"):
                    continue
                full = os.path.join(STATES_DIR, j2_rel)
                usage.setdefault(full, set()).add(os.path.relpath(path, STATES_DIR))

    return {k: sorted(v) for k, v in usage.items()}


def collect_macro_data_usage():
    """Scan Jinja macros for data file imports — used as indirect consumers."""
    usage = {}
    for path in glob.glob(os.path.join(STATES_DIR, "_macros_*.jinja")):
        with open(path) as f:
            content = f.read()
        for match in IMPORT_YAML_RE.finditer(content):
            rel = match.group(1)
            if not rel.startswith("data/"):
                continue
            full = os.path.join(STATES_DIR, rel)
            macro_name = os.path.basename(path)
            usage.setdefault(full, set()).add(macro_name)
    for path in glob.glob(os.path.join(STATES_DIR, "_imports.jinja")):
        with open(path) as f:
            content = f.read()
        for match in IMPORT_YAML_RE.finditer(content):
            rel = match.group(1)
            if not rel.startswith("data/"):
                continue
            full = os.path.join(STATES_DIR, rel)
            macro_name = os.path.basename(path)
            usage.setdefault(full, set()).add(macro_name)
    return {k: sorted(v) for k, v in usage.items()}


def _fmt_list(items, empty_text):
    return ", ".join(f"`{item}`" for item in sorted(set(items))) if items else empty_text


def generate_data_inventory_docs(summaries, usage):
    info_map = {rel: info for rel, info in summaries}
    eng = [
        HEADER,
        "# Data Inventory\n",
        "Mapping of `states/data/*.yaml` sections to consumer states.\n",
    ]
    rus = [
        HEADER,
        "# Инвентарь data-файлов\n",
        "Связь `states/data/*.yaml` и состояний, которые их импортируют.\n",
    ]

    for rel in sorted(info_map):
        data_key = os.path.join(STATES_DIR, rel.removeprefix("states/"))
        consumers = usage.get(data_key, [])
        sections = info_map[rel]

        eng.append(f"\n## `{rel}`")
        eng.append(f"**Used by:** {_fmt_list(consumers, '_Unused_')}\n")
        if isinstance(sections, str):
            eng.append(f"_{sections}_\n")
        else:
            for section in sections:
                eng.append(f"- {section}")
            eng.append("")

        rus.append(f"\n## `{rel}`")
        rus.append(f"**Используют:** {_fmt_list(consumers, '_Не используется_')}\n")
        if isinstance(sections, str):
            rus.append(f"_{sections}_\n")
        else:
            for section in sections:
                rus.append(f"- {section}")
            rus.append("")

    return "\n".join(eng) + "\n", "\n".join(rus) + "\n"


# --- Module index generation (LLM-oriented YAML) ---

_SECRET_RE = re.compile(r"(?:tg_secret|gopass_secret)\s*\(\s*'([^']+)'")
_SERVICE_FILE_RE = re.compile(r"user_service_file\s*\(\s*'[^']+'\s*,\s*'([^']+)'")
_SERVICE_ENABLE_RE = re.compile(
    r"user_service_enable\s*\(\s*'[^']+'(?:\s*,\s*start_now\s*=\s*\[([^\]]*)\])?"
)
_CONTAINER_RE = re.compile(r"container_service\s*\(\s*'([^']+)'")
_CONFIG_RE = re.compile(r"salt://(configs/[^\s'\"]+)")
_DATA_IMPORT_RE = re.compile(r"import_yaml\s+['\"](data/[^'\"]+)['\"]")
_NPM_PKG_RE = re.compile(r"npm_pkg\s*\(\s*'[^']+'\s*,\s*pkg\s*=\s*'([^']+)'")
_DOC_COMMENT_RE = re.compile(r"\{#\s*(.*?)\s*#\}", re.DOTALL)


def _scan_state_source(relpath):
    """Scan a .sls file for secrets, services, configs, data refs."""
    full = os.path.join(STATES_DIR, relpath.removeprefix("states/"))
    secrets = []
    services = []
    configs = []
    data_files = []
    purpose = ""
    try:
        with open(full) as f:
            src = f.read()
    except (OSError, IOError):
        return secrets, services, configs, data_files, purpose

    secrets = sorted(set(_SECRET_RE.findall(src)))
    # Collapse spaces inside Jinja {{ }} to avoid regex truncation on spaces
    _jinja_safe = re.sub(r"\{\{\s*(.*?)\s*\}\}", r"{{\1}}", src)
    configs = sorted(set(_CONFIG_RE.findall(_jinja_safe)))
    data_files = sorted(set(o for o in _DATA_IMPORT_RE.findall(src) if o.startswith("data/")))

    # Also scan referenced config .j2 templates for data imports
    for config_rel in configs:
        config_path = os.path.join(STATES_DIR, config_rel)
        if not config_path.endswith(".j2"):
            continue
        if not os.path.isfile(config_path):
            continue
        try:
            with open(config_path) as cf:
                config_src = cf.read()
        except (OSError, IOError):
            continue
        for j2_match in _DATA_IMPORT_RE.finditer(config_src):
            j2_rel = j2_match.group(1)
            if j2_rel.startswith("data/"):
                data_files.append(j2_rel)

    data_files = sorted(set(data_files))

    for m in _SERVICE_FILE_RE.finditer(src):
        services.append(m.group(1))
    for m in _CONTAINER_RE.finditer(src):
        services.append(f"{m.group(1)}.container")
    for m in _NPM_PKG_RE.finditer(src):
        services.append(f"{m.group(1)} (npm)")

    # First line after header or doc comment as purpose hint
    doc_m = _DOC_COMMENT_RE.search(src)
    if doc_m:
        purpose = doc_m.group(1).strip().split("\n")[0].strip()

    return secrets, sorted(set(services)), configs, data_files, purpose


def _find_tests_for_state(state_name):
    """Heuristic: find test files that likely test a given state."""
    base = os.path.basename(state_name).removeprefix("test_").removesuffix(".sls").replace(".", "_")
    matches = []
    for f in sorted(glob.glob("tests/test_*.py")):
        name = os.path.basename(f).removeprefix("test_").removesuffix(".py")
        if name == base or name == base.replace("_", ""):
            matches.append(f)
    return matches


def _find_tests_for_data(data_basename):
    base = data_basename.removesuffix(".yaml")
    match = f"tests/test_{base}.py"
    return [match] if os.path.isfile(match) else []


def generate_module_index(state_results, macros, summaries, usage):
    """Generate docs/module-index.yaml — LLM-oriented project map."""

    index = {
        "version": 1,
        "generated": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
    }

    # States
    states_list = []
    for rel, state_ids, includes, requires, guards in state_results:
        state_name = _state_name_from_relpath(rel)
        secrets, services, configs, data_files, purpose = _scan_state_source(rel)
        tests = _find_tests_for_state(rel)

        entry = {
            "id": state_name,
            "path": f"states/{rel}" if not rel.startswith("states/") else rel,
            "purpose": purpose,
            "feature_gate": sorted(set(guards)) if guards else None,
            "secrets": secrets if secrets else None,
            "includes": sorted(set(includes)) if includes else None,
            "data_files": data_files if data_files else None,
            "services": services if services else None,
            "configs": configs if configs else None,
            "tests": tests if tests else None,
        }
        # Remove None fields for compactness
        entry = {k: v for k, v in entry.items() if v is not None}
        states_list.append(entry)
    index["states"] = states_list

    # Macros
    macros_list = []
    by_file = {}
    for name, params, src, doc in macros:
        by_file.setdefault(src, []).append(name)
    for src in sorted(by_file):
        macros_list.append({
            "id": os.path.basename(src).replace(".jinja", ""),
            "path": src,
            "provides": by_file[src],
        })
    index["macros"] = macros_list

    # Python scripts
    py_scripts = []
    for f in sorted(glob.glob("scripts/*.py")):
        py_scripts.append({
            "path": f,
            "purpose": _purpose_from_docstring(f),
        })
    index["scripts_py"] = py_scripts

    # Shell scripts
    sh_scripts = []
    for f in sorted(glob.glob("scripts/*.sh") + glob.glob("scripts/*.zsh")):
        sh_scripts.append({
            "path": f,
            "purpose": _purpose_from_shebang_comment(f),
        })
    index["scripts_sh"] = sh_scripts

    # Data files
    data_list = []
    for rel, _ in summaries:
        data_key = os.path.join(STATES_DIR, rel.removeprefix("states/"))
        consumers = usage.get(data_key, [])
        data_list.append({
            "path": rel,
            "consumers": sorted(consumers) if consumers else None,
        })
    index["data_files"] = data_list

    # Test files
    test_list = []
    for f in sorted(glob.glob("tests/test_*.py")):
        test_list.append({
            "path": f,
        })
    index["test_files"] = test_list

    # Docs
    docs_list = []
    for f in sorted(glob.glob("docs/*.md")):
        docs_list.append({
            "path": f,
            "purpose": _purpose_from_first_heading(f),
        })
    index["docs"] = docs_list

    return yaml.dump(index, default_flow_style=False, allow_unicode=True, sort_keys=False)


def validate_knowledge_references(knowledge_path, state_results, macros, summaries):
    """Cross-validate knowledge.yaml related_entities/related_docs against project entities.

    Returns list of (severity, message) tuples.
    """
    with open(knowledge_path) as f:
        knowledge = yaml.safe_load(f)

    # Build entity lookup sets
    state_ids = set()
    for rel, _state_ids, _includes, _requires, _guards in state_results:
        state_ids.add(_state_name_from_relpath(rel))

    macro_ids = set()
    for _name, _params, src, _doc in macros:
        macro_ids.add(os.path.basename(src).replace(".jinja", ""))

    script_basenames = set()
    for f in glob.glob("scripts/*.py"):
        script_basenames.add(os.path.basename(f))
    for f in glob.glob("scripts/*.sh") + glob.glob("scripts/*.zsh"):
        script_basenames.add(os.path.basename(f))

    data_basenames = set()
    for rel, _info in summaries:
        data_basenames.add(os.path.basename(rel))
        data_basenames.add(rel)

    service_names = set()
    for rel, _state_ids, _includes, _requires, _guards in state_results:
        _s, services, _c, _d, _p = _scan_state_source(rel)
        for svc in services:
            service_names.add(svc)
            service_names.add(svc.split(".")[0].split(" (")[0])

    all_doc_ids = set()
    for cat in knowledge.get("categories", {}).values():
        for doc_id in cat.get("docs", {}):
            all_doc_ids.add(doc_id)

    issues = []

    for cat_name, category in knowledge.get("categories", {}).items():
        for doc_id, doc in category.get("docs", {}).items():
            for ref in doc.get("related_entities", []):
                if ref in ("state:*", "macro:*"):
                    continue
                if ref == "macro:_macros_*.jinja":
                    if not any(fnmatch.fnmatch(mid, "_macros_*") for mid in macro_ids):
                        issues.append(("error", f"[{cat_name}/{doc_id}] {ref}: no matching macros"))
                    continue

                prefix, name = ref.split(":", 1)

                if prefix == "state":
                    if name not in state_ids:
                        alt = name.replace("-", "_").replace(".", "_")
                        if alt not in state_ids:
                            issues.append((
                                "warn",
                                f"[{cat_name}/{doc_id}] {ref}: state not found in module index",
                            ))
                elif prefix == "macro":
                    mid = name.replace(".jinja", "")
                    if mid not in macro_ids:
                        issues.append(("error", f"[{cat_name}/{doc_id}] {ref}: macro not found"))
                elif prefix == "data":
                    if name not in data_basenames:
                        issues.append((
                            "error",
                            f"[{cat_name}/{doc_id}] {ref}: data file not found",
                        ))
                elif prefix == "script":
                    if name not in script_basenames:
                        issues.append(("error", f"[{cat_name}/{doc_id}] {ref}: script not found"))
                elif prefix == "service":
                    if name not in service_names:
                        issues.append((
                            "warn",
                            f"[{cat_name}/{doc_id}] {ref}: "
                            "service not found in any state definition",
                        ))

            for ref in doc.get("related_docs", []):
                if ref not in all_doc_ids:
                    issues.append((
                        "error",
                        f"[{cat_name}/{doc_id}] related_docs '{ref}': "
                        "target doc not found in knowledge.yaml",
                    ))

    return issues


def _purpose_from_docstring(path):
    try:
        with open(path) as f:
            src = f.read()
        m = re.search(r'"""(.+?)"""', src, re.DOTALL)
        if m:
            return m.group(1).strip().split("\n")[0].strip()
    except Exception:
        pass
    return ""


def _purpose_from_shebang_comment(path):
    try:
        with open(path) as f:
            lines = f.readlines()
        for line in lines[:5]:
            line = line.strip()
            if line.startswith("# ") and not line.startswith("#!"):
                return line[2:].strip()
    except Exception:
        pass
    return ""


def _purpose_from_first_heading(path):
    try:
        with open(path) as f:
            for line in f:
                if line.startswith("# "):
                    return line[2:].strip()
    except Exception:
        pass
    return ""


def _log(pretty, msg: str) -> None:
    if pretty:
        pretty.info(msg)
    else:
        print(msg)


def main():
    if not os.path.isdir(STATES_DIR):
        print(f"Error: {STATES_DIR} not found. Run from project root.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(MEMORY_DIR, exist_ok=True)
    os.makedirs(DOCS_DIR, exist_ok=True)

    try:
        from lib.pretty import pretty
    except ImportError:
        pretty = None

    if pretty:
        pretty.section("Indexing Salt States")

    # 1. Macros
    jinja_files = sorted(glob.glob(os.path.join(STATES_DIR, "_macros_*.jinja")))
    macros = parse_macros(jinja_files)
    macros_md = generate_macros_md(macros)
    macros_path = os.path.join(MEMORY_DIR, "salt-macros.md")
    with open(macros_path, "w") as f:
        f.write(macros_md)
    _log(pretty, f"Wrote {macros_path} ({len(macros)} macros, {macros_md.count(chr(10))} lines)")

    # 2. States
    sls_files = [record.relpath for record in discover_state_files(STATES_DIR)]
    state_results = render_states(sls_files)
    rendered_ok = sum(1 for _, ids, _, _, _ in state_results if ids)
    states_md = generate_states_md(state_results)
    states_path = os.path.join(MEMORY_DIR, "salt-states.md")
    with open(states_path, "w") as f:
        f.write(states_md)
    n_lines = states_md.count(chr(10))
    _log(
        pretty,
        f"Wrote {states_path} ({len(sls_files)} files, {rendered_ok} rendered, {n_lines} lines)",
    )

    # 3. Data files
    summaries = summarize_data_files()
    data_md = generate_data_md(summaries)
    data_path = os.path.join(MEMORY_DIR, "salt-data.md")
    with open(data_path, "w") as f:
        f.write(data_md)
    _log(pretty, f"Wrote {data_path} ({len(summaries)} files, {data_md.count(chr(10))} lines)")

    usage = collect_data_usage()
    macro_usage = collect_macro_data_usage()
    for k, v in macro_usage.items():
        usage.setdefault(k, set()).update(v)
    usage = {k: sorted(v) for k, v in usage.items()}
    eng_inventory, _ = generate_data_inventory_docs(summaries, usage)
    inventory_path = os.path.join(DOCS_DIR, "data-inventory.md")
    with open(inventory_path, "w") as f:
        f.write(eng_inventory)
    _log(pretty, f"Wrote {inventory_path}")

    # 4. State dependency map docs
    graph, reverse, guards_map = build_state_graph(state_results)
    eng_map, _ = generate_state_map_docs(graph, reverse, guards_map)
    eng_path = os.path.join(DOCS_DIR, "state-map.md")
    with open(eng_path, "w") as f:
        f.write(eng_map)
    _log(pretty, f"Wrote {eng_path}")

    # 5. Module index (LLM-oriented YAML)
    module_index_yaml = generate_module_index(state_results, macros, summaries, usage)
    module_index_path = os.path.join(DOCS_DIR, "module-index.yaml")
    with open(module_index_path, "w") as f:
        f.write(module_index_yaml)
    _log(pretty, f"Wrote {module_index_path}")

    write_knowledge_base(macros, state_results, summaries)

    # 6. Cross-validate knowledge.yaml references
    knowledge_path = os.path.join(DOCS_DIR, "knowledge.yaml")
    if os.path.isfile(knowledge_path):
        issues = validate_knowledge_references(knowledge_path, state_results, macros, summaries)
        if issues:
            errs = sum(1 for sev, _ in issues if sev == "error")
            warns = sum(1 for sev, _ in issues if sev == "warn")
            msg = f"knowledge.yaml validation: {errs} errors, {warns} warnings"
            if pretty:
                if errs:
                    pretty.fail(msg)
                else:
                    pretty.warn(msg)
                for severity, msg_line in issues:
                    if severity == "error":
                        pretty.fail(f"  {msg_line}")
                    else:
                        pretty.warn(f"  {msg_line}")
            else:
                print(f"\n{msg}")
                for severity, msg_line in issues:
                    print(f"  [{severity.upper()}] {msg_line}")
        else:
            if pretty:
                pretty.ok("knowledge.yaml validation: all references OK")
            else:
                print("knowledge.yaml validation: all references OK")

if __name__ == "__main__":
    main()
