#!/bin/bash
# Append NixOS generation entries to /efi/limine.cfg
# Called by Salt state or nixos-rebuild hook.
# Mounts the NixOS btrfs partition, discovers generations from boot.json,
# and writes Limine linux-protocol entries.

set -euo pipefail

NIXOS_PARTUUID="4d2585cf-07cf-4ad8-aa52-3c62d780cd03"
NIXOS_FS_UUID="10d42115-ab09-4142-bb50-9ec56fcda509"
MNT="/tmp/limine-nixos-mnt"
CONFIG="/efi/limine.cfg"
MARKER="# @nixos-generations"
MAX_GENS=5

cleanup() { mountpoint -q "$MNT" 2>/dev/null && sudo umount "$MNT" 2>/dev/null || true; rmdir "$MNT" 2>/dev/null || true; }
trap cleanup EXIT

mkdir -p "$MNT"
sudo mount -o ro,subvol=/ "PARTUUID=${NIXOS_PARTUUID}" "$MNT" 2>/dev/null || {
    echo "limine-generations: NixOS partition not found, skipping NixOS entries" >&2
    exit 0
}

PROFILES_DIR="$MNT/nix/var/nix/profiles"
[ -d "$PROFILES_DIR" ] || { echo "limine-generations: no NixOS profiles dir" >&2; exit 0; }

# Strip existing NixOS entries from config (between marker and end)
sudo sed -i "/^${MARKER}/,\$d" "$CONFIG" 2>/dev/null

# Write marker
echo "" | sudo tee -a "$CONFIG" > /dev/null
echo "# ─── NixOS generations (auto-generated by scripts/limine-generations.sh) ────" | sudo tee -a "$CONFIG" > /dev/null
echo "$MARKER" | sudo tee -a "$CONFIG" > /dev/null
echo "" | sudo tee -a "$CONFIG" > /dev/null

count=0
for profile_link in $(ls -1rv "$PROFILES_DIR"/system-*-link 2>/dev/null); do
    [ $count -ge $MAX_GENS ] && break
    gen_num=$(basename "$profile_link" | sed -E 's/system-([0-9]+)-link/\1/')
    boot_json="$profile_link/boot.json"
    [ -f "$boot_json" ] || continue

    label=$(jq -r '.["org.nixos.bootspec.v1"].label // "NixOS Generation '"$gen_num"'"' "$boot_json" 2>/dev/null || echo "NixOS Generation $gen_num")
    kernel=$(jq -r '.["org.nixos.bootspec.v1"].kernel' "$boot_json" 2>/dev/null)
    initrd=$(jq -r '.["org.nixos.bootspec.v1"].initrd' "$boot_json" 2>/dev/null)
    init=$(jq -r '.["org.nixos.bootspec.v1"].init' "$boot_json" 2>/dev/null)
    params=$(jq -r '.["org.nixos.bootspec.v1"].kernelParams | join(" ")' "$boot_json" 2>/dev/null)

    [ -n "$kernel" ] && [ -n "$initrd" ] || continue

    cat <<ENTRY | sudo tee -a "$CONFIG" > /dev/null
:NixOS (Generation ${gen_num} — ${label})
    PROTOCOL=linux
    COMMENT=NixOS Generation ${gen_num}
    KERNEL_CMDLINE=root=PARTUUID=${NIXOS_PARTUUID} rw init=${init} ${params}
    KERNEL_PATH=uuid(${NIXOS_FS_UUID})://${kernel#/}
    MODULE_PATH=uuid(${NIXOS_FS_UUID})://${initrd#/}

ENTRY
    count=$((count + 1))
done

echo "limine-generations: appended $count NixOS generation(s)"
