local terminal = "kitty --single-instance --class term"
local clipboard_manager = "zsh -c 'pkill \"wl-paste --watch cliphist store\"; wl-paste --watch cliphist store'"

hl.on("hyprland.start", function()
  hl.exec_cmd("~/.local/bin/unlock")
  hl.exec_cmd("dunst")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("systemctl --user start --no-block hyprpolkitagent.service")
  hl.exec_cmd("systemctl --user restart --no-block hyprscratch.service")
  hl.exec_cmd("systemctl --user restart --no-block wl.service || wl-daemon &")
  hl.exec_cmd(terminal)
  hl.exec_cmd("swayosd-server")
  hl.exec_cmd(clipboard_manager)
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY HYPRLAND_INSTANCE_SIGNATURE && systemctl --user restart --no-block quickshell.service")
  hl.exec_cmd("nicotine")
  hl.exec_cmd("~/.local/bin/hypr-focus-hist")
  hl.exec_cmd("~/.local/bin/gpg-warmup")
  hl.exec_cmd("systemctl --user start --no-block vicinae.service")
  hl.exec_cmd("systemctl --user start --no-block surfingkeys-server.service")
  hl.exec_cmd("qs -c overview")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_XDG_DESKTOP_PORTAL GTK_THEME QT_STYLE_OVERRIDE QT_QPA_PLATFORMTHEME")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_XDG_DESKTOP_PORTAL GTK_THEME QT_STYLE_OVERRIDE QT_QPA_PLATFORMTHEME")
end)
