# Class patterns (shared)

# Workspace routing classes
$daw = match:class ^(REAPER|Renoise)$
$dev = match:class ^(nwim)$
$doc = match:class ^(org.pwmt.zathura)$
$dw = match:class ^(org.nicotine_plus.Nicotine)$
$games = match:class ^(steam|Steam|steam_app_\d+|gamescope)$
$im = match:class ^(im.riot.Riot)$
$keyboard = match:class ^(Bazecor|wootility-lekker|Vial|via)$
$notes = match:class ^(Obsidian)$
$obs = match:class ^(obs)$
$patchbay = match:class ^(qpwgraph|Carla2)$
$pic = match:class ^swayimg$
$remote = match:class ^(Vmware-view|xfreerdp|remmina|org.remmina.Remmina)$
$term = match:class ^(term)$
$vid = match:class ^(mpv)$
$vm = match:class ^(.virt-manager-wrapped|qemu-system-x86_64|Qemu-system-x86_64)$
$web = match:class (?i)^(zen|floorp|one\.ablaze\.floorp|floorpdeveloperedition|firefox(?:[ -]?developer[ -]?edition)?|org\.mozilla\.firefox(?:[ -]?developer[ -]?edition)?|librewolf|io\.gitlab\.librewolf-community|chromium(?:-browser)?|org\.chromium\.chromium|ungoogled-chromium(?:-dev)?|brave(?:-browser(?:-(?:beta|nightly))?)?|com\.brave\.browser|vivaldi(?:-(?:stable|snapshot))?|opera(?:-(?:beta|developer))?|thorium-browser|com\.thorium\.thorium|mullvad-browser|com\.mullvad\.browser|palemoon|net\.palemoon\.palemoon|qutebrowser|org\.qutebrowser\.qutebrowser|falkon|org\.kde\.falkon|midori|epiphany|org\.gnome\.epiphany|google-chrome(?:-(?:stable|beta|unstable))?|com\.google\.chrome|microsoft-edge(?:-(?:beta|dev|canary))?|com\.microsoft\.edge)$
$wine = match:class ^(com.usebottles.bottles)$

# WinBoat workspace routing
$winboat = match:class ^(winboat|WinBoat)$

# Scratchpad classes
$im_scratchpad = match:class ^(KotatogramDesktop|Skype|Slack|TelegramDesktop|org.telegram.desktop|zoom)$
$music_scratchpad = match:class ^(ncmpcpp|rmpc|music)$
$mixer_scratchpad = match:class ^(mixer|pipemixer)$
$torrment_scratchpad = match:class ^(torrment)$
$teardown_scratchpad = match:class ^(teardown)$
