hl.config({ autogenerated = false })

border_size = 1
col_border_active_base = "rgba(00285981)"
col_border_inactive = "rgba(00000000)"
rounding = 0
rounding_power = 0
opacity_active = 1.0
opacity_inactive = 1.0
shadow_color = 0xaa005faf
blur_size = 9
blur_passes = 2
blur_vibrancy = 0

hl.monitor({ output = "DP-2", mode = "3840x2160@240", position = "0x0", scale = 2, vrr = 3, bitdepth = 10, cm = "auto" })
hl.monitor({ output = "DP-1", disabled = true })

hl.env("GDK_SCALE", "2")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("XCURSOR_SIZE", "23")
hl.env("GDK_BACKEND", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("QT_XDG_DESKTOP_PORTAL", "1")
hl.env("GTK_USE_PORTAL", "1")
hl.env("GTK_THEME", "Flight-Dark-GTK")
hl.env("XCURSOR_THEME", "Alkano-aio")

hl.config({
  general = {
    gaps_in = 0, gaps_out = 0, border_size = border_size,
    col = {
      active_border = { colors = { col_border_active_base, col_border_active_base }, angle = 45 },
      inactive_border = col_border_inactive,
    },
    resize_on_border = false, allow_tearing = true, layout = "scrolling",
  },
  decoration = {
    rounding = rounding, rounding_power = rounding_power,
    active_opacity = opacity_active, inactive_opacity = opacity_inactive,
    shadow = { enabled = false, range = 4, render_power = 1, color = shadow_color },
    blur = { enabled = true, size = blur_size, passes = blur_passes, vibrancy = blur_vibrancy },
  },
  input = {
    kb_layout = "us,ru", kb_variant = "", kb_model = "", kb_options = "", kb_rules = "",
    follow_mouse = 1, sensitivity = 0, repeat_rate = 35, repeat_delay = 250,
    touchpad = { natural_scroll = true, disable_while_typing = true, clickfinger_behavior = true },
  },
  misc = {
    disable_hyprland_logo = false, enable_anr_dialog = false, force_default_wallpaper = 0,
    font_family = "Iosevka", splash_font_family = "Iosevka",
    vrr = 3, enable_swallow = true, middle_click_paste = false, disable_autoreload = 0,
  },
  cursor = { sync_gsettings_theme = true, no_hardware_cursors = true, min_refresh_rate = 240, inactive_timeout = 1, hide_on_key_press = true, warp_on_change_workspace = false },
  render = { direct_scanout = 2 },
  xwayland = { force_zero_scaling = true, use_nearest_neighbor = true },
  dwindle = { preserve_split = true, smart_resizing = false, smart_split = false },
  master = { new_status = "master", mfact = 0.7 },
  scrolling = { column_width = 0.5, fullscreen_on_one_column = true, explicit_column_widths = "0.5, 1.0", focus_fit_method = 1, follow_focus = true, follow_min_visible = 0.5, direction = "right" },
})

local M4 = "SUPER"
local M1 = "Alt"
local C = "Control"
local SH = "Shift"

hl.bind(M4 .. "+S", hl.dsp.exec_cmd("hyprctl switchxkblayout current next"))
hl.bind(M1 .. "+Tab", hl.dsp.exec_cmd("~/.local/bin/hypr-focus-hist --switch"))
hl.bind(M4 .. "+Tab", hl.dsp.exec_cmd("qs ipc -c overview call overview toggle"))
hl.bind(M4 .. "+" .. C .. "+backslash", hl.dsp.window.resize({ x = 640, y = 480 }))
hl.bind(M4 .. "+" .. SH .. "+Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind(M4 .. "+" .. SH .. "+Tab", hl.dsp.window.bring_to_top())
hl.bind(M4 .. "+c", hl.dsp.exec_cmd("~/.local/bin/clip"))
hl.bind(M4 .. "+Escape", hl.dsp.window.close())
hl.bind(M4 .. "+r", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(M4 .. "+Return", hl.dsp.exec_cmd("kitty --single-instance"), { locked = true })
hl.bind(M4 .. "+p", hl.dsp.exec_cmd("pkill rofi || ~/.local/bin/rofi-pass-2col"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+p", hl.dsp.exec_cmd("pkill rofi || tessen"), { locked = true })
hl.bind(M4 .. "+mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(M4 .. "+mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(M4 .. "+mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(M4 .. "+mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Scratchpad toggles
hl.bind(M4 .. "+d", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle teardown"))
hl.bind(M4 .. "+e", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle im"))
hl.bind(M4 .. "+f", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle music"))
hl.bind(M4 .. "+t", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle torrment"))
hl.bind(M4 .. "+" .. C .. "+p", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle mixer"))

-- App launchers
hl.bind(M4 .. "+w", hl.dsp.exec_cmd('raise --match "class:regex=(?i)^(zen|firefox)" --launch zen-browser'))
hl.bind(M4 .. "+" .. SH .. "+w", hl.dsp.exec_cmd('raise --match "class:regex=^floorp$" --launch floorp'))
hl.bind(M4 .. "+x", hl.dsp.exec_cmd('raise --match "class:regex=^term$" --launch "kitty --single-instance --class term"'))
hl.bind(M4 .. "+q", hl.dsp.exec_cmd('raise --match "class:regex=^nwim$" --launch "kitty --single-instance --class nwim -e v"'))
hl.bind(M4 .. "+b", hl.dsp.exec_cmd('raise --match "class:regex=^mpv$" --launch "~/.local/bin/pl video"'))
hl.bind(M4 .. "+" .. C .. "+c", hl.dsp.exec_cmd('raise --match "class:regex=^swayimg$" --launch "swayimg ~/dw"'))
hl.bind(M4 .. "+" .. SH .. "+c", hl.dsp.exec_cmd("wl random ~/pic/wl"))
hl.bind(M4 .. "+" .. C .. "+v", hl.dsp.exec_cmd('raise --match "class:regex=^Bazecor$" --launch "bazecor"'))
hl.bind(M4 .. "+g", hl.dsp.exec_cmd('raise --match "class:regex=^(steam|steam_app.*|gamescope)$" --launch steam'))
hl.bind(M4 .. "+" .. SH .. "+g", hl.dsp.exec_cmd('raise --match "class:regex=^(lutris|net%.lutris%.Lutris)$" --launch "flatpak run net.lutris.Lutris"'))
hl.bind(M4 .. "+o", hl.dsp.exec_cmd('raise --match "class:regex=^org%.pwmt%.zathura$" --launch "zathura"'))
hl.bind(M4 .. "+" .. C .. "+o", hl.dsp.exec_cmd('raise --match "class:regex=^(obs|com%.obsproject%.Studio)$" --launch "obs"'))
hl.bind(M4 .. "+" .. C .. "+n", hl.dsp.exec_cmd('raise --match "class:regex=^(Obsidian|md%.obsidian%.Obsidian)$" --launch "flatpak run md.obsidian.Obsidian"'))

-- Focus / scrolling
hl.bind(M4 .. "+equal", hl.dsp.layout("colresize +conf"))
hl.bind(M4 .. "+" .. SH .. "+equal", hl.dsp.layout("fit all"))
hl.bind(M4 .. "+h", hl.dsp.layout("focus l"))
hl.bind(M4 .. "+j", hl.dsp.layout("focus d"))
hl.bind(M4 .. "+k", hl.dsp.layout("focus u"))
hl.bind(M4 .. "+l", hl.dsp.layout("focus r"))
hl.bind(M4 .. "+" .. SH .. "+h", hl.dsp.window.move({ direction = "l" }))
hl.bind(M4 .. "+" .. SH .. "+j", hl.dsp.window.move({ direction = "d" }))
hl.bind(M4 .. "+" .. SH .. "+k", hl.dsp.window.move({ direction = "u" }))
hl.bind(M4 .. "+" .. SH .. "+l", hl.dsp.window.move({ direction = "r" }))

-- Media
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume +5"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume -5"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness +10"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness -10"), { repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+w", hl.dsp.exec_cmd("~/.local/bin/pl cmd play-pause"), { locked = true })
hl.bind(M4 .. "+comma", hl.dsp.exec_cmd("~/.local/bin/pl cmd previous"), { locked = true })
hl.bind(M4 .. "+period", hl.dsp.exec_cmd("~/.local/bin/pl cmd next"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+i", hl.dsp.exec_cmd("~/.local/bin/pl vol mute"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+o", hl.dsp.exec_cmd("~/.local/bin/pl vol unmute"), { locked = true })
hl.bind(M4 .. "+m", hl.dsp.exec_cmd("~/.local/bin/music-rename current"), { locked = true })

-- Misc
hl.bind(M1 .. "+g", hl.dsp.exec_cmd("~/.local/bin/hypr-win-list"))
hl.bind(M1 .. "+backslash", hl.dsp.exec_cmd("~/.local/bin/hypr-win-list"))
hl.bind(M4 .. "+" .. SH .. "+m", hl.dsp.exec_cmd("~/.local/bin/main-menu"))
hl.bind(M4 .. "+slash", hl.dsp.exec_cmd("~/.local/bin/hypr-shortcuts"))
hl.bind(M4 .. "+" .. SH .. "+S", hl.dsp.exec_cmd("hyprquickframe"))
hl.bind(M4 .. "+" .. SH .. "+r", hl.dsp.exec_cmd('shot="$HOME/pic/shots/satty-$(date \'+%Y%m%d-%H.%M.%S\').png"; grim "$shot" && pic-info "$shot"'))
hl.bind(M4 .. "+" .. SH .. "+" .. C .. "+r", hl.dsp.exec_cmd('shot="$HOME/pic/shots/satty-$(date \'+%Y%m%d-%H.%M.%S\').png"; grim -g "$(slurp)" "$shot" && pic-info "$shot"'))
hl.bind(M4 .. "+" .. SH .. "+v", hl.dsp.exec_cmd("~/.local/bin/screenrec screen"))
hl.bind(M4 .. "+" .. SH .. "+" .. C .. "+v", hl.dsp.exec_cmd("~/.local/bin/screenrec area"))
hl.bind(M1 .. "+q", hl.dsp.exec_cmd("vicinae toggle"))
hl.bind("Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"))
hl.bind(M4 .. "+apostrophe", hl.dsp.exec_cmd("~/.local/bin/hypr-fix"))
hl.bind(M4 .. "+" .. SH .. "+apostrophe", hl.dsp.exec_cmd("~/.local/bin/sys-relief"))
hl.bind(M4 .. "+i", hl.dsp.exec_cmd("wlr-which-key"))
hl.bind(M4 .. "+" .. M1 .. "+p", hl.dsp.exec_cmd("~/.local/bin/switch-proxy"))
hl.bind(M4 .. "+n", hl.dsp.exec_cmd("dunstctl history-pop"))
hl.bind(M4 .. "+space", hl.dsp.exec_cmd("dunstctl close-all"), { locked = true })
hl.bind(M4 .. "+" .. C .. "+d", hl.dsp.layout("splitratio -0.1"), { release = true })
hl.bind(M4 .. "+" .. C .. "+f", hl.dsp.layout("splitratio +0.1"), { release = true })

local function submap_resets()
  hl.bind("escape", hl.dsp.submap("reset"))
  hl.bind(C .. "+c", hl.dsp.submap("reset"))
  hl.bind(C .. "+q", hl.dsp.submap("reset"))
  hl.bind("q", hl.dsp.submap("reset"))
end

local function bind_reset(key, fn)
  hl.bind(key, fn)
  hl.bind(key, hl.dsp.submap("reset"))
end

local function binde_reset(key, fn)
  hl.bind(key, fn, { release = true })
  hl.bind(key, hl.dsp.submap("reset"), { release = true })
end

-- Submap: resize
hl.bind(M4 .. "+" .. M1 .. "+r", hl.dsp.submap("resize"))
hl.define_submap("resize", "reset", function()
  submap_resets()
  hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { release = true })
  hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { release = true })
  hl.bind("up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { release = true })
  hl.bind("down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { release = true })
  hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { release = true })
  hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { release = true })
  hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { release = true })
  hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { release = true })
  hl.bind(SH .. "+l", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { release = true })
  hl.bind(SH .. "+h", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { release = true })
  hl.bind(SH .. "+k", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { release = true })
  hl.bind(SH .. "+j", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { release = true })
  hl.bind("equal", hl.dsp.exec_cmd("~/.local/bin/hypr-resize-proportional +10"), { release = true })
  hl.bind("minus", hl.dsp.exec_cmd("~/.local/bin/hypr-resize-proportional -10"), { release = true })
  hl.bind(SH .. "+equal", hl.dsp.exec_cmd("~/.local/bin/hypr-resize-proportional +25"), { release = true })
  hl.bind(SH .. "+minus", hl.dsp.exec_cmd("~/.local/bin/hypr-resize-proportional -25"), { release = true })
  hl.bind("Return", hl.dsp.submap("reset"))
end)

-- Submap: selectors
hl.bind(M4 .. "+Alt+S", hl.dsp.submap("selectors"))
hl.define_submap("selectors", "reset", function()
  submap_resets()
  bind_reset("w", hl.dsp.exec_cmd("hyde-selector wallpaper"))
  bind_reset("t", hl.dsp.exec_cmd("hyde-selector theme"))
  bind_reset("a", hl.dsp.exec_cmd("hyde-selector animation"))
  bind_reset("e", hl.dsp.exec_cmd('vicinae "vicinae://extensions/vicinae/core/search-emojis"'))
  bind_reset("c", hl.dsp.exec_cmd('vicinae "vicinae://extensions/vicinae/calculator/index"'))
  hl.bind("Return", hl.dsp.submap("reset"))
  hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Submap: special
hl.bind(M1 .. "+e", hl.dsp.submap("special"))
hl.define_submap("special", "reset", function()
  submap_resets()
  binde_reset("r", hl.dsp.exec_cmd('raise --match "class:regex=^REAPER$" --launch "GDK_BACKEND=x11 reaper"'))
  binde_reset("q", hl.dsp.exec_cmd('raise --match "class:regex=^qpwgraph$" --launch "qpwgraph"'))
  binde_reset("d", hl.dsp.exec_cmd('raise --match "class:regex=^org%.nicotine_plus%.Nicotine$" --launch "nicotine"'))
  binde_reset(SH .. "+q", hl.dsp.exec_cmd('raise --match "class:regex=^Carla2$" --launch "carla"'))
  binde_reset(SH .. "+l", hl.dsp.exec_cmd("hyprctl switchxkblayout current 0 && hyprlock"))
  binde_reset("e", hl.dsp.window.float({ action = "toggle" }))
  binde_reset("f", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
  binde_reset("z", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
  hl.bind("semicolon", hl.dsp.submap("reset"), { release = true })
  binde_reset(SH .. "+w", hl.dsp.exec_cmd("pkill iwmenu || iwmenu --launcher rofi"))
  binde_reset("o", hl.dsp.exec_cmd('raise --match "match:title ^(Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload)(.*)$"'))
end)

-- Submap: tiling
hl.bind(M4 .. "+minus", hl.dsp.submap("tiling"))
hl.define_submap("tiling", "reset", function()
  submap_resets()
  hl.bind(SH .. "+h", hl.dsp.window.move({ direction = "l" }))
  hl.bind(SH .. "+j", hl.dsp.window.move({ direction = "d" }))
  hl.bind(SH .. "+k", hl.dsp.window.move({ direction = "u" }))
  hl.bind(SH .. "+l", hl.dsp.window.move({ direction = "r" }))
  hl.bind("equal", hl.dsp.layout("colresize +conf"))
  hl.bind("minus", hl.dsp.layout("colresize -conf"))
  hl.bind("1", hl.dsp.layout("colresize exact 0.25"))
  hl.bind("2", hl.dsp.layout("colresize exact 0.33"))
  hl.bind("3", hl.dsp.layout("colresize exact 0.5"))
  hl.bind("4", hl.dsp.layout("colresize exact 0.66"))
  hl.bind("5", hl.dsp.layout("colresize exact 0.75"))
  hl.bind("6", hl.dsp.layout("colresize exact 1.0"))
  hl.bind("bracketright", hl.dsp.layout("colresize +50"), { release = true })
  hl.bind("bracketleft", hl.dsp.layout("colresize -50"), { release = true })
  hl.bind("p", hl.dsp.layout("promote"))
  hl.bind(C .. "+h", hl.dsp.layout("swapcol l"))
  hl.bind(C .. "+l", hl.dsp.layout("swapcol r"))
  hl.bind("f", hl.dsp.layout("fit active"))
  hl.bind(SH .. "+f", hl.dsp.layout("fit all"))
  hl.bind("h", hl.dsp.layout("move -200"), { release = true })
  hl.bind("l", hl.dsp.layout("move +200"), { release = true })
  hl.bind(SH .. "+bracketleft", hl.dsp.layout("move -600"), { release = true })
  hl.bind(SH .. "+bracketright", hl.dsp.layout("move +600"), { release = true })
  hl.bind("t", hl.dsp.layout("togglefit"))
end)

-- Submap: wallpaper
hl.bind(M4 .. "+" .. SH .. "+y", hl.dsp.submap("wallpaper"))
hl.define_submap("wallpaper", "reset", function()
  submap_resets()
  hl.bind("y", hl.dsp.exec_cmd("wl random ~/pic/wl"))
  hl.bind(M4 .. "+y", hl.dsp.exec_cmd("wl random ~/pic/wl"))
  hl.bind(SH .. "+w", hl.dsp.submap("reset"))
end)

-- Submap: vpn
hl.bind(M4 .. "+v", hl.dsp.submap("vpn"))
hl.define_submap("vpn", "reset", function()
  submap_resets()
  binde_reset("h", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle hiddify"))
  binde_reset("a", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle amnezia"))
  binde_reset("f", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle flclashx"))
  binde_reset("n", hl.dsp.exec_cmd("~/.local/bin/scratchpad-toggle v2rayn"))
end)
