hl.config({ autogenerated = false })

hl.monitor({
  output = "DP-2",
  mode = "3840x2160@240",
  position = "0x0",
  scale = 2,
  vrr = 3,
  bitdepth = 10,
  cm = "auto",
})

hl.monitor({
  output = "DP-1",
  disabled = true,
})

hl.env("GDK_SCALE", "2")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("XCURSOR_SIZE", "23")
hl.env("GDK_BACKEND", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("QT_XDG_DESKTOP_PORTAL", "1")
hl.env("GTK_USE_PORTAL", "1")
hl.env("GTK_THEME", "Flight-Dark-GTK")
hl.env("XCURSOR_THEME", "Alkano-aio")

hl.bind("SUPER+Q", hl.dsp.exec_cmd("kitty"))
